-- ==============================================================================
-- SCRIPT COMPLETO DE CRIAÇÃO DO BANCO DE DADOS - ENFERMAGEM PRO
-- Execute este script no SQL Editor do Supabase (https://supabase.com/dashboard)
-- ==============================================================================

-- 1. EXTENSÕES
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. TABELA DE PERFIS (PROFILES)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    first_name TEXT,
    last_name TEXT,
    avatar_url TEXT,
    bio TEXT,
    profession TEXT,
    specializations TEXT[],
    role TEXT DEFAULT 'user',
    status TEXT DEFAULT 'active',
    plan TEXT DEFAULT 'free',
    access_expires_at TIMESTAMP WITH TIME ZONE,
    plan_start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_ip TEXT,
    location TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Profiles select policy') THEN
        CREATE POLICY "Profiles select policy" ON public.profiles FOR SELECT TO authenticated USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Profiles update self') THEN
        CREATE POLICY "Profiles update self" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Profiles insert self') THEN
        CREATE POLICY "Profiles insert self" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
    END IF;
END $$;

-- 3. TABELA DE QUESTÕES (QUESTIONS)
CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT,
    banca TEXT,
    question TEXT NOT NULL,
    options JSONB NOT NULL,
    correctAnswer TEXT NOT NULL,
    explanation TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'questions' AND policyname = 'Questions select all') THEN
        CREATE POLICY "Questions select all" ON public.questions FOR SELECT TO authenticated USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'questions' AND policyname = 'Questions admin all') THEN
        CREATE POLICY "Questions admin all" ON public.questions FOR ALL TO authenticated USING (
            EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
        );
    END IF;
END $$;

-- 4. RESPOSTAS DO USUÁRIO (USER_QUESTION_ANSWERS)
CREATE TABLE IF NOT EXISTS public.user_question_answers (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    question_id BIGINT REFERENCES public.questions(id) ON DELETE CASCADE,
    is_correct BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.user_question_answers ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_question_answers' AND policyname = 'Users manage own answers') THEN
        CREATE POLICY "Users manage own answers" ON public.user_question_answers FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_question_answers' AND policyname = 'Admins view answers') THEN
        CREATE POLICY "Admins view answers" ON public.user_question_answers FOR SELECT TO authenticated USING (
            EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
        );
    END IF;
END $$;

-- 5. SIMULADOS DO USUÁRIO (USER_SIMULATIONS)
CREATE TABLE IF NOT EXISTS public.user_simulations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    score INT NOT NULL,
    total_questions INT NOT NULL,
    percentage INT NOT NULL,
    time_taken_seconds INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.user_simulations ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_simulations' AND policyname = 'Users manage own simulations') THEN
        CREATE POLICY "Users manage own simulations" ON public.user_simulations FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
    END IF;
END $$;

-- 6. FAVORITOS DO USUÁRIO (USER_FAVORITES)
CREATE TABLE IF NOT EXISTS public.user_favorites (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    item_id TEXT NOT NULL,
    item_type TEXT NOT NULL,
    item_title TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, item_id)
);

ALTER TABLE public.user_favorites ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_favorites' AND policyname = 'Users manage own favorites') THEN
        CREATE POLICY "Users manage own favorites" ON public.user_favorites FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
    END IF;
END $$;

-- 7. CONQUISTAS E MEDALHAS (USER_BADGES)
CREATE TABLE IF NOT EXISTS public.user_badges (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    badge_code TEXT NOT NULL,
    earned_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, badge_code)
);

ALTER TABLE public.user_badges ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_badges' AND policyname = 'Users manage own badges') THEN
        CREATE POLICY "Users manage own badges" ON public.user_badges FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
    END IF;
END $$;

-- 8. FLASHCARDS
CREATE TABLE IF NOT EXISTS public.flashcards (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    deck_category TEXT NOT NULL,
    front_content TEXT NOT NULL,
    back_content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.flashcards ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'flashcards' AND policyname = 'Flashcards select all') THEN
        CREATE POLICY "Flashcards select all" ON public.flashcards FOR SELECT TO authenticated USING (true);
    END IF;
END $$;

-- 9. PROGRESSO DE FLASHCARDS (USER_FLASHCARD_PROGRESS)
CREATE TABLE IF NOT EXISTS public.user_flashcard_progress (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    flashcard_id UUID REFERENCES public.flashcards(id) ON DELETE CASCADE,
    next_review TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    interval_days INT DEFAULT 1,
    ease_factor FLOAT DEFAULT 2.5,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, flashcard_id)
);

ALTER TABLE public.user_flashcard_progress ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_flashcard_progress' AND policyname = 'Users manage own flashcard progress') THEN
        CREATE POLICY "Users manage own flashcard progress" ON public.user_flashcard_progress FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
    END IF;
END $$;

-- 10. COMENTÁRIOS NAS QUESTÕES (COMMENTS)
CREATE TABLE IF NOT EXISTS public.comments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    question_id BIGINT REFERENCES public.questions(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'comments' AND policyname = 'Comments select all') THEN
        CREATE POLICY "Comments select all" ON public.comments FOR SELECT TO authenticated USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'comments' AND policyname = 'Users insert own comments') THEN
        CREATE POLICY "Users insert own comments" ON public.comments FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'comments' AND policyname = 'Users delete own comments or admin') THEN
        CREATE POLICY "Users delete own comments or admin" ON public.comments FOR DELETE TO authenticated USING (
            auth.uid() = user_id OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
        );
    END IF;
END $$;

-- 11. BLOCO DE NOTAS (NOTES)
CREATE TABLE IF NOT EXISTS public.notes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT,
    content TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'notes' AND policyname = 'Users manage own notes') THEN
        CREATE POLICY "Users manage own notes" ON public.notes FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
    END IF;
END $$;

-- 12. GRIFOS DE TEXTO (USER_HIGHLIGHTS)
CREATE TABLE IF NOT EXISTS public.user_highlights (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    document_id TEXT NOT NULL,
    selected_text TEXT NOT NULL,
    color TEXT DEFAULT 'yellow',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.user_highlights ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_highlights' AND policyname = 'Users manage own highlights') THEN
        CREATE POLICY "Users manage own highlights" ON public.user_highlights FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
    END IF;
END $$;

-- 13. LOGS DE ACESSO E TEMPO DIÁRIO
CREATE TABLE IF NOT EXISTS public.access_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    path TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.access_logs ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'access_logs' AND policyname = 'Users insert own access logs') THEN
        CREATE POLICY "Users insert own access logs" ON public.access_logs FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'access_logs' AND policyname = 'Admins view access logs') THEN
        CREATE POLICY "Admins view access logs" ON public.access_logs FOR SELECT TO authenticated USING (
            EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
        );
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.daily_activity_time (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    activity_date DATE DEFAULT CURRENT_DATE,
    seconds INT DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (user_id, activity_date)
);

ALTER TABLE public.daily_activity_time ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'daily_activity_time' AND policyname = 'Users manage own daily time') THEN
        CREATE POLICY "Users manage own daily time" ON public.daily_activity_time FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
    END IF;
END $$;

-- 14. PROGRESSO EM CASOS CLÍNICOS
CREATE TABLE IF NOT EXISTS public.user_case_progress (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    case_id TEXT NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (user_id, case_id)
);

ALTER TABLE public.user_case_progress ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_case_progress' AND policyname = 'Users manage own case progress') THEN
        CREATE POLICY "Users manage own case progress" ON public.user_case_progress FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
    END IF;
END $$;

-- 15. MATERIAIS DE ESTUDO (PDFs)
CREATE TABLE IF NOT EXISTS public.study_materials (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL,
    file_url TEXT NOT NULL,
    file_size TEXT,
    page_count INT,
    is_premium BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.study_materials ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'study_materials' AND policyname = 'Study materials select all') THEN
        CREATE POLICY "Study materials select all" ON public.study_materials FOR SELECT TO authenticated USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'study_materials' AND policyname = 'Study materials admin all') THEN
        CREATE POLICY "Study materials admin all" ON public.study_materials FOR ALL TO authenticated USING (
            EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
        );
    END IF;
END $$;

-- 16. BLOCOS DE ESTUDO E SESSÕES (CRONOGRAMA/PLANNER)
CREATE TABLE IF NOT EXISTS public.user_study_blocks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    category_name TEXT NOT NULL,
    duration_minutes INT DEFAULT 60,
    color TEXT DEFAULT 'blue',
    order_index INT DEFAULT 0,
    day_of_week INT DEFAULT NULL,
    is_completed BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.user_study_blocks ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_study_blocks' AND policyname = 'Users manage own blocks') THEN
        CREATE POLICY "Users manage own blocks" ON public.user_study_blocks FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.user_study_sessions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    category_name TEXT NOT NULL,
    duration_seconds INT DEFAULT 0,
    completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.user_study_sessions ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_study_sessions' AND policyname = 'Users manage own sessions') THEN
        CREATE POLICY "Users manage own sessions" ON public.user_study_sessions FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
    END IF;
END $$;

-- 17. TEMAS DA APLICAÇÃO (APP_THEME)
CREATE TABLE IF NOT EXISTS public.app_theme (
    id INT PRIMARY KEY DEFAULT 1,
    settings JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.app_theme ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'app_theme' AND policyname = 'App theme public select') THEN
        CREATE POLICY "App theme public select" ON public.app_theme FOR SELECT TO authenticated USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'app_theme' AND policyname = 'App theme admin all') THEN
        CREATE POLICY "App theme admin all" ON public.app_theme FOR ALL TO authenticated USING (
            EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
        );
    END IF;
END $$;

-- 18. VÍDEOS DA VIDEOTECA (VIDEOS)
CREATE TABLE IF NOT EXISTS public.videos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    youtube_id TEXT NOT NULL,
    title TEXT NOT NULL,
    author TEXT,
    category TEXT NOT NULL,
    duration TEXT,
    is_public BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.videos ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'videos' AND policyname = 'Videos select public') THEN
        CREATE POLICY "Videos select public" ON public.videos FOR SELECT TO authenticated USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'videos' AND policyname = 'Videos admin all') THEN
        CREATE POLICY "Videos admin all" ON public.videos FOR ALL TO authenticated USING (
            EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
        );
    END IF;
END $$;

-- 19. LOGS DE WEBHOOK (KIWIFY)
CREATE TABLE IF NOT EXISTS public.webhook_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    email TEXT,
    evento TEXT,
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.webhook_logs ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'webhook_logs' AND policyname = 'Admins view webhook logs') THEN
        CREATE POLICY "Admins view webhook logs" ON public.webhook_logs FOR SELECT TO authenticated USING (
            EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
        );
    END IF;
END $$;

-- ==============================================================================
-- BUCKETS DE ARMAZENAMENTO (STORAGE)
-- ==============================================================================
INSERT INTO storage.buckets (id, name, public) VALUES ('avatars', 'avatars', true) ON CONFLICT DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('theme', 'theme', true) ON CONFLICT DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('concurso_pdfs', 'concurso_pdfs', true) ON CONFLICT DO NOTHING;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'Avatars public select') THEN
        CREATE POLICY "Avatars public select" ON storage.objects FOR SELECT TO public USING (bucket_id = 'avatars');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'Avatars auth insert') THEN
        CREATE POLICY "Avatars auth insert" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'avatars');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'PDFs public select') THEN
        CREATE POLICY "PDFs public select" ON storage.objects FOR SELECT TO public USING (bucket_id = 'concurso_pdfs');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'PDFs public insert') THEN
        CREATE POLICY "PDFs public insert" ON storage.objects FOR INSERT TO public WITH CHECK (bucket_id = 'concurso_pdfs');
    END IF;
END $$;

-- ==============================================================================
-- FUNÇÕES RPC (STORED PROCEDURES)
-- ==============================================================================

-- Busca ID do usuário pelo e-mail
CREATE OR REPLACE FUNCTION public.get_user_id_by_email(email_input TEXT)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    user_id_val UUID;
BEGIN
    SELECT id INTO user_id_val FROM auth.users WHERE LOWER(email) = LOWER(email_input) LIMIT 1;
    RETURN user_id_val;
END;
$$;

-- Ranking Global
CREATE OR REPLACE FUNCTION public.get_global_ranking()
RETURNS TABLE (
    user_id UUID,
    first_name TEXT,
    last_name TEXT,
    avatar_url TEXT,
    score BIGINT,
    accuracy INT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    WITH user_answers AS (
        SELECT 
            u.user_id,
            COUNT(u.id) AS total_q,
            COUNT(CASE WHEN u.is_correct THEN 1 END) AS correct_q
        FROM public.user_question_answers u
        GROUP BY u.user_id
    ),
    user_sims AS (
        SELECT 
            s.user_id,
            SUM(s.score) AS sim_correct,
            SUM(s.total_questions) AS sim_total
        FROM public.user_simulations s
        GROUP BY s.user_id
    )
    SELECT 
        p.id AS user_id,
        COALESCE(p.first_name, 'Usuário') AS first_name,
        COALESCE(p.last_name, '') AS last_name,
        p.avatar_url,
        COALESCE(ua.correct_q, 0) + COALESCE(us.sim_correct, 0) AS score,
        CASE 
            WHEN (COALESCE(ua.total_q, 0) + COALESCE(us.sim_total, 0)) > 0 
            THEN ROUND(((COALESCE(ua.correct_q, 0) + COALESCE(us.sim_correct, 0))::NUMERIC / (COALESCE(ua.total_q, 0) + COALESCE(us.sim_total, 0))::NUMERIC) * 100)::INT
            ELSE 0 
        END AS accuracy
    FROM public.profiles p
    LEFT JOIN user_answers ua ON p.id = ua.user_id
    LEFT JOIN user_sims us ON p.id = us.user_id
    WHERE (COALESCE(ua.correct_q, 0) + COALESCE(us.sim_correct, 0)) > 0
    ORDER BY score DESC, accuracy DESC
    LIMIT 100;
END;
$$;

-- Sorteio de Questões Aleatórias
CREATE OR REPLACE FUNCTION public.get_random_questions(limit_count INT DEFAULT 1)
RETURNS SETOF public.questions
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT * FROM public.questions ORDER BY RANDOM() LIMIT limit_count;
$$;

-- Incrementar Atividade Diária
CREATE OR REPLACE FUNCTION public.increment_user_activity(seconds_to_add INT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    INSERT INTO public.daily_activity_time (user_id, activity_date, seconds, updated_at)
    VALUES (auth.uid(), CURRENT_DATE, seconds_to_add, NOW())
    ON CONFLICT (user_id, activity_date)
    DO UPDATE SET 
        seconds = public.daily_activity_time.seconds + EXCLUDED.seconds,
        updated_at = NOW();
END;
$$;

-- Busca de Detalhes dos Usuários (Admin)
CREATE OR REPLACE FUNCTION public.get_all_user_details()
RETURNS TABLE (
    id UUID,
    first_name TEXT,
    last_name TEXT,
    role TEXT,
    status TEXT,
    plan TEXT,
    avatar_url TEXT,
    email TEXT,
    access_expires_at TIMESTAMP WITH TIME ZONE,
    plan_start_date TIMESTAMP WITH TIME ZONE,
    last_ip TEXT,
    location TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        u.id,
        p.first_name,
        p.last_name,
        COALESCE(p.role, 'user') AS role,
        COALESCE(p.status, 'active') AS status,
        COALESCE(p.plan, 'free') AS plan,
        p.avatar_url,
        u.email::TEXT,
        p.access_expires_at,
        p.plan_start_date,
        p.last_ip,
        p.location
    FROM auth.users u
    LEFT JOIN public.profiles p ON u.id = p.id
    ORDER BY u.created_at DESC;
END;
$$;

-- Estatísticas Detalhadas de Desempenho do Usuário
CREATE OR REPLACE FUNCTION public.get_detailed_performance_stats(p_user_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    result JSONB;
BEGIN
    SELECT jsonb_build_object(
        'categories', (
            SELECT COALESCE(jsonb_agg(cat_row), '[]'::jsonb)
            FROM (
                SELECT 
                    q.category,
                    COUNT(a.id) AS total_answered,
                    COUNT(CASE WHEN a.is_correct THEN 1 END) AS total_correct
                FROM public.user_question_answers a
                JOIN public.questions q ON a.question_id = q.id
                WHERE a.user_id = p_user_id
                GROUP BY q.category
            ) cat_row
        ),
        'simulations', (
            SELECT COALESCE(jsonb_agg(sim_row), '[]'::jsonb)
            FROM (
                SELECT score, total_questions, percentage, time_taken_seconds, created_at
                FROM public.user_simulations
                WHERE user_id = p_user_id
                ORDER BY created_at ASC
            ) sim_row
        ),
        'total_time_seconds', COALESCE((SELECT SUM(seconds) FROM public.daily_activity_time WHERE user_id = p_user_id), 0),
        'total_simulations_count', COALESCE((SELECT COUNT(*) FROM public.user_simulations WHERE user_id = p_user_id), 0)
    ) INTO result;
    
    RETURN result;
END;
$$;

-- ==============================================================================
-- FIM DO SCRIPT
-- ==============================================================================