-- Pacote de 20 questões de alta relevância para concursos
-- Foco: Legislação do SUS, Urgência e Emergência, Segurança do Paciente, SAE

INSERT INTO public.questions (id, category, question, options, "correctAnswer", explanation, banca) VALUES
-- Legislação do SUS
(491, 'Legislação do SUS', 'A Lei 8.142/90 estabelece a composição paritária para os Conselhos de Saúde. Como é essa distribuição?', '[{"id": "A", "text": "50% usuários, 50% profissionais de saúde."}, {"id": "B", "text": "50% usuários, 25% trabalhadores da saúde, 25% governo e prestadores."}, {"id": "C", "text": "25% para cada segmento: usuários, trabalhadores, gestores e prestadores."}, {"id": "D", "text": "Um terço para cada segmento: usuários, trabalhadores e gestores."}]', 'B', 'A composição paritária dos Conselhos e Conferências de Saúde é de 50% de representantes dos usuários, 25% de representantes dos trabalhadores da saúde e 25% de representantes do governo e prestadores de serviços.', 'FGV'),
(492, 'Legislação do SUS', 'De acordo com o Decreto 7.508/2011, qual serviço é considerado a porta de entrada preferencial e ordenadora da Rede de Atenção à Saúde?', '[{"id": "A", "text": "Os hospitais de referência."}, {"id": "B", "text": "Os serviços de urgência e emergência."}, {"id": "C", "text": "A Atenção Primária."}, {"id": "D", "text": "Os ambulatórios de especialidades."}]', 'C', 'O Decreto 7.508/11 reforça o papel da Atenção Primária (ou Básica) como a principal porta de entrada, centro de comunicação, coordenadora do cuidado e ordenadora da rede de atenção à saúde.', 'Cebraspe'),
(493, 'Legislação do SUS', 'Segundo a Política Nacional de Atenção Básica (PNAB), qual é uma atribuição específica do Agente Comunitário de Saúde (ACS)?', '[{"id": "A", "text": "Realizar consulta de enfermagem e prescrever medicações."}, {"id": "B", "text": "Realizar curativos e administrar medicamentos injetáveis."}, {"id": "C", "text": "Trabalhar com adscrição de famílias em base geográfica definida (microárea) e realizar visitas domiciliares."}, {"id": "D", "text": "Coordenar a Unidade Básica de Saúde."}]', 'C', 'A principal atribuição do ACS é o trabalho no território, com a adscrição de um número definido de famílias em sua microárea, realizando o acompanhamento contínuo por meio de visitas domiciliares e servindo como elo entre a comunidade e a equipe de saúde.', 'Vunesp'),
(494, 'Legislação do SUS', 'O princípio da Integralidade no SUS significa:', '[{"id": "A", "text": "Que todos os cidadãos têm direito ao acesso aos serviços de saúde."}, {"id": "B", "text": "Que o indivíduo deve ser visto como um todo, considerando ações de promoção, prevenção, tratamento e reabilitação."}, {"id": "C", "text": "Que os recursos devem ser distribuídos de forma desigual, priorizando quem mais precisa."}, {"id": "D", "text": "Que a gestão do sistema é de responsabilidade exclusiva dos municípios."}]', 'B', 'A Integralidade compreende o indivíduo em sua totalidade (biopsicossocial) e articula as ações de saúde em todos os níveis de atenção (promoção, prevenção, cura e reabilitação), garantindo uma assistência completa e contínua.', 'IBFC'),
(495, 'Legislação do SUS', 'Para que um município receba os recursos do Fundo Nacional de Saúde de forma regular e automática, a Lei 8.142/90 exige, entre outros, a existência de:', '[{"id": "A", "text": "Hospital municipal e frota de ambulâncias."}, {"id": "B", "text": "Fundo de Saúde, Conselho de Saúde e Plano de Saúde."}, {"id": "C", "text": "No mínimo 10 Equipes de Saúde da Família."}, {"id": "D", "text": "Secretário de Saúde com formação na área da saúde."}]', 'B', 'O Art. 4º da Lei 8.142/90 estabelece os requisitos para a transferência de recursos, que incluem a existência de um Fundo de Saúde, um Conselho de Saúde atuante e com composição paritária, e um Plano de Saúde aprovado.', 'FCC'),

-- Urgência e Emergência
(496, 'Urgência e Emergência', 'Na avaliação primária do politraumatizado (XABCDE), qual é a prioridade imediata ao abordar a letra ''A'' (Airway)?', '[{"id": "A", "text": "Administrar oxigênio em alto fluxo."}, {"id": "B", "text": "Verificar a perviedade das vias aéreas com proteção da coluna cervical."}, {"id": "C", "text": "Puncionar dois acessos venosos calibrosos."}, {"id": "D", "text": "Avaliar o nível de consciência pela Escala de Glasgow."}]', 'B', 'A letra ''A'' do mnemônico significa Vias Aéreas (Airway). A prioridade é garantir que a via aérea esteja aberta e desobstruída, sempre associada à imobilização e proteção da coluna cervical, pois uma via aérea obstruída leva à morte em minutos.', 'EBSERH'),
(497, 'Urgência e Emergência', 'Um paciente de 70kg sofreu queimaduras de 2º e 3º grau na face anterior do tronco e em todo o membro superior direito. Segundo a Regra dos Nove e a Fórmula de Parkland, qual o volume total de Ringer Lactato a ser infundido nas primeiras 24h?', '[{"id": "A", "text": "3.960 ml."}, {"id": "B", "text": "5.040 ml."}, {"id": "C", "text": "7.560 ml."}, {"id": "D", "text": "10.080 ml."}]', 'C', 'SCQ: Tronco anterior (18%) + Membro superior direito (9%) = 27%. Fórmula de Parkland: 4ml x Peso (kg) x %SCQ. Cálculo: 4 x 70 x 27 = 7.560 ml. Metade (3.780ml) nas primeiras 8h e a outra metade nas 16h seguintes.', 'Cesgranrio'),
(498, 'Urgência e Emergência', 'No atendimento a um paciente com Infarto Agudo do Miocárdio com Supradesnivelamento de ST (IAMCSST), qual é a meta de tempo ''porta-balão''?', '[{"id": "A", "text": "10 minutos."}, {"id": "B", "text": "30 minutos."}, {"id": "C", "text": "90 minutos."}, {"id": "D", "text": "120 minutos."}]', 'C', 'O tempo porta-balão refere-se ao intervalo entre a chegada do paciente ao hospital e a insuflação do balão para desobstruir a artéria coronária (Angioplastia Primária). A meta é que esse tempo seja inferior a 90 minutos para maximizar a preservação do músculo cardíaco.', 'AOCP'),
(499, 'Urgência e Emergência', 'Um paciente com AVC isquêmico agudo chega à emergência com PA de 200/110 mmHg e não é candidato à trombólise. Qual a conduta em relação à pressão arterial?', '[{"id": "A", "text": "Reduzir a PA agressivamente para 120/80 mmHg com anti-hipertensivo IV."}, {"id": "B", "text": "Manter a hipertensão permissiva, tratando apenas se PA > 220/120 mmHg."}, {"id": "C", "text": "Administrar Captopril sublingual imediatamente."}, {"id": "D", "text": "Iniciar diurético para reduzir a volemia e a pressão."}]', 'B', 'No AVC isquêmico agudo, a hipertensão pode ser um mecanismo compensatório para manter a perfusão na área de penumbra isquêmica. Se o paciente não for trombolisado, a recomendação é tratar a PA apenas se ela exceder 220/120 mmHg, e a redução deve ser cautelosa.', 'IBFC'),
(500, 'Urgência e Emergência', 'Um paciente na UTI apresenta febre, taquicardia e hipotensão refratária à reposição volêmica. A pele está quente e avermelhada. Qual tipo de choque é mais provável?', '[{"id": "A", "text": "Choque Cardiogênico."}, {"id": "B", "text": "Choque Hipovolêmico."}, {"id": "C", "text": "Choque Obstrutivo."}, {"id": "D", "text": "Choque Distributivo (Séptico)."} ]', 'D', 'O choque séptico é um tipo de choque distributivo. Na fase inicial (fase quente), ocorre vasodilatação periférica maciça, resultando em pele quente e avermelhada, taquicardia e hipotensão, apesar do débito cardíaco poder estar normal ou aumentado.', 'FGV'),

-- Segurança do Paciente
(501, 'Segurança do Paciente', 'A Meta 1 de Segurança do Paciente preconiza a identificação correta. Qual é a recomendação mínima para identificar um paciente antes de um procedimento?', '[{"id": "A", "text": "Perguntar o nome completo do paciente."}, {"id": "B", "text": "Verificar o número do leito."}, {"id": "C", "text": "Utilizar pelo menos dois identificadores, como nome completo e data de nascimento."}, {"id": "D", "text": "Conferir o nome do paciente na pulseira de identificação."}]', 'C', 'A recomendação é usar no mínimo dois identificadores únicos para o paciente, como nome completo e data de nascimento. O número do leito ou do quarto NUNCA deve ser usado como identificador, pois é variável.', 'Vunesp'),
(502, 'Segurança do Paciente', 'Qual dos seguintes grupos de medicamentos é classificado como de ''alta vigilância'' ou potencialmente perigoso, exigindo dupla checagem?', '[{"id": "A", "text": "Analgésicos comuns e antitérmicos."}, {"id": "B", "text": "Vitaminas e suplementos."}, {"id": "C", "text": "Insulinas, anticoagulantes e eletrólitos concentrados (KCl)."}, {"id": "D", "text": "Antibióticos de uso comum."}]', 'C', 'Medicamentos de alta vigilância são aqueles que possuem um risco aumentado de causar danos significativos aos pacientes em caso de erro. Insulinas, heparina, varfarina, quimioterápicos e eletrólitos como o Cloreto de Potássio (KCl) são exemplos clássicos.', 'Cebraspe'),
(503, 'Segurança do Paciente', 'O ''Time Out'' ou Pausa Cirúrgica, parte do checklist de cirurgia segura, deve ser realizado em qual momento?', '[{"id": "A", "text": "Antes da indução anestésica."}, {"id": "B", "text": "Imediatamente antes da incisão cirúrgica."}, {"id": "C", "text": "No final da cirurgia, antes do fechamento da pele."}, {"id": "D", "text": "Na sala de recuperação pós-anestésica."}]', 'B', 'O Time Out é a segunda etapa do checklist e consiste em uma pausa realizada por toda a equipe cirúrgica, imediatamente antes da incisão, para confirmar verbalmente o paciente, o procedimento, o sítio cirúrgico e a lateralidade corretos.', 'FCC'),
(504, 'Segurança do Paciente', 'A higienização das mãos é a principal medida para prevenir infecções. Qual dos ''5 Momentos'' da OMS se refere à higienização ANTES de realizar um procedimento limpo/asséptico?', '[{"id": "A", "text": "Momento 1 (Antes do contato com o paciente)."}, {"id": "B", "text": "Momento 2 (Antes da realização de procedimento limpo/asséptico)."}, {"id": "C", "text": "Momento 3 (Após risco de exposição a fluidos corporais)."}, {"id": "D", "text": "Momento 4 (Após contato com o paciente)."}]', 'B', 'O Momento 2 visa proteger o paciente de microrganismos que podem entrar em seu corpo durante um procedimento, como a inserção de um cateter ou a realização de um curativo.', 'IBFC'),
(505, 'Segurança do Paciente', 'Um erro de medicação que foi interceptado antes de atingir o paciente (ex: enfermeiro percebe a troca de ampolas ao preparar) é classificado como:', '[{"id": "A", "text": "Evento adverso."}, {"id": "B", "text": "Incidente sem dano."}, {"id": "C", "text": "Near miss (Quase erro)."}, {"id": "D", "text": "Circunstância de risco."}]', 'C', 'Um ''near miss'' ou ''quase erro'' é um incidente que não atingiu o paciente, seja por acaso ou por uma intervenção oportuna. É um evento valioso para a aprendizagem e melhoria de processos, devendo ser notificado.', 'AOCP'),

-- SAE
(510, 'Sistematização da Assistência (SAE)', 'Qual a finalidade da etapa de Avaliação no Processo de Enfermagem?', '[{"id": "A", "text": "Coletar novos dados sobre o paciente."}, {"id": "B", "text": "Formular os diagnósticos de enfermagem."}, {"id": "C", "text": "Verificar se os resultados esperados foram alcançados e se o plano de cuidados precisa de ajustes."}, {"id": "D", "text": "Executar as intervenções prescritas pela equipe."}]', 'C', 'A Avaliação é a quinta e última etapa, onde o enfermeiro compara o estado atual do paciente com os resultados esperados (definidos no planejamento). É um processo contínuo que determina a eficácia das intervenções e a necessidade de modificar o plano.', 'IBFC'),
(506, 'Sistematização da Assistência (SAE)', 'Qual é a ordem correta das 5 etapas do Processo de Enfermagem, segundo a Resolução COFEN 358/2009?', '[{"id": "A", "text": "Diagnóstico, Planejamento, Coleta de Dados, Implementação, Avaliação."}, {"id": "B", "text": "Coleta de Dados, Planejamento, Diagnóstico, Implementação, Avaliação."}, {"id": "C", "text": "Coleta de Dados, Diagnóstico, Planejamento, Implementação, Avaliação."}, {"id": "D", "text": "Planejamento, Coleta de Dados, Diagnóstico, Avaliação, Implementação."}]', 'C', 'A sequência lógica e sistemática do Processo de Enfermagem é: 1. Coleta de Dados (Histórico); 2. Diagnóstico de Enfermagem; 3. Planejamento; 4. Implementação (Execução); 5. Avaliação.', 'Vunesp'),
(507, 'Sistematização da Assistência (SAE)', 'A estrutura ''Problema relacionado a Etiologia evidenciado por Sinais e Sintomas'' (P.E.S.) é utilizada para a formulação de qual tipo de diagnóstico de enfermagem da NANDA-I?', '[{"id": "A", "text": "Diagnóstico de Risco."}, {"id": "B", "text": "Diagnóstico de Promoção da Saúde."}, {"id": "C", "text": "Diagnóstico com Foco no Problema (Real)."}, {"id": "D", "text": "Diagnóstico de Síndrome."}]', 'C', 'O formato P.E.S. é a estrutura clássica para um diagnóstico com foco no problema (ou real), pois descreve um problema de saúde existente, sua causa (fatores relacionados) e as evidências que o confirmam (características definidoras).', 'FGV'),
(508, 'Sistematização da Assistência (SAE)', 'No planejamento da assistência, qual a diferença entre NOC e NIC?', '[{"id": "A", "text": "NOC são os diagnósticos e NIC são as prescrições."}, {"id": "B", "text": "NOC são os resultados esperados (metas) e NIC são as intervenções (ações) para alcançá-los."}, {"id": "C", "text": "NOC são as ações do enfermeiro e NIC são as ações do técnico."}, {"id": "D", "text": "NOC é a avaliação e NIC é o planejamento."}]', 'B', 'NOC (Nursing Outcomes Classification) refere-se à classificação dos Resultados de Enfermagem, ou seja, as metas que se deseja alcançar com o paciente. NIC (Nursing Interventions Classification) refere-se à classificação das Intervenções de Enfermagem, ou seja, as ações que serão realizadas.', 'Cebraspe'),
(509, 'Sistematização da Assistência (SAE)', 'A etapa de Implementação do Processo de Enfermagem é de responsabilidade de:', '[{"id": "A", "text": "Apenas do Enfermeiro."}, {"id": "B", "text": "Apenas do Técnico de Enfermagem."}, {"id": "C", "text": "Toda a equipe de enfermagem (Enfermeiro, Técnico e Auxiliar), sob supervisão do Enfermeiro."}, {"id": "D", "text": "Da equipe multiprofissional (médico, fisioterapeuta, etc.)."}]', 'C', 'A etapa de Implementação envolve a execução das ações prescritas pelo enfermeiro. Essas ações são realizadas por toda a equipe de enfermagem, cada um dentro de suas competências legais, e sempre sob a supervisão e orientação do enfermeiro.', 'FCC');