-- Pacote de 20 questões para reforçar categorias de base
-- Foco: Saúde da Mulher, Saúde da Criança, Biossegurança/CME, Fundamentos de Enfermagem

INSERT INTO public.questions (id, category, question, options, "correctAnswer", explanation, banca) VALUES
-- Saúde da Mulher
(471, 'Saúde da Mulher', 'Segundo o Ministério da Saúde, qual o número mínimo de consultas de pré-natal recomendado para uma gestação de baixo risco?', '[{"id": "A", "text": "Quatro consultas, uma por trimestre."}, {"id": "B", "text": "Cinco consultas, sendo duas no último trimestre."}, {"id": "C", "text": "Seis consultas, com periodicidade crescente ao final da gestação."}, {"id": "D", "text": "Oito consultas, sendo duas por mês."}]', 'C', 'O Ministério da Saúde recomenda um mínimo de 6 consultas de pré-natal, sendo: mensais até a 28ª semana, quinzenais entre 28ª e 36ª semana, e semanais a partir da 36ª semana.', 'FGV'),
(472, 'Saúde da Mulher', 'No trabalho de parto, o período que se inicia com a saída da placenta e termina uma hora após é conhecido como:', '[{"id": "A", "text": "Período de dilatação."}, {"id": "B", "text": "Período expulsivo."}, {"id": "C", "text": "Secundamento ou dequitação."}, {"id": "D", "text": "Quarto período ou Período de Greenberg."}]', 'D', 'O quarto período, ou Período de Greenberg, corresponde à primeira hora após a dequitação (saída da placenta). É um período crítico para vigilância de hemorragia pós-parto, onde se avalia o ''globo de segurança de Pinard''.', 'Cebraspe'),
(473, 'Saúde da Mulher', 'Durante a avaliação do puerpério, o enfermeiro observa a evolução dos lóquios. Qual a sequência correta de sua evolução?', '[{"id": "A", "text": "Rubra (vermelho), Alba (branco), Serosa (rosado)."}, {"id": "B", "text": "Serosa (rosado), Rubra (vermelho), Alba (branco)."}, {"id": "C", "text": "Rubra (vermelho), Serosa (rosado), Alba (branco)."}, {"id": "D", "text": "Alba (branco), Serosa (rosado), Rubra (vermelho)."}]', 'C', 'A evolução normal dos lóquios é: Loquia rubra (sangue vivo, até 3-4 dias), seguida pela Loquia serosa (rosada/acastanhada, até o 10º dia) e, por fim, a Loquia alba (esbranquiçada, após o 10º dia).', 'Vunesp'),
(474, 'Saúde da Mulher', 'As diretrizes do INCA para rastreamento do câncer de colo de útero recomendam o início da coleta do Papanicolau em qual faixa etária?', '[{"id": "A", "text": "A partir do início da vida sexual."}, {"id": "B", "text": "Aos 18 anos, para todas as mulheres."}, {"id": "C", "text": "Aos 25 anos, para mulheres que já tiveram atividade sexual."}, {"id": "D", "text": "Aos 40 anos, juntamente com a mamografia."}]', 'C', 'O rastreamento deve iniciar aos 25 anos para mulheres com vida sexual ativa. A periodicidade é anual nos dois primeiros exames e, se ambos negativos, passa a ser a cada 3 anos. A coleta antes dos 25 anos não é recomendada devido à alta prevalência de lesões transitórias por HPV.', 'IBFC'),
(475, 'Saúde da Mulher', 'Na administração de Sulfato de Magnésio para prevenção de eclâmpsia, qual é o primeiro sinal clínico de intoxicação que a enfermagem deve monitorar?', '[{"id": "A", "text": "Hipertensão arterial."}, {"id": "B", "text": "Depressão respiratória (FR < 12 irpm)."}, {"id": "C", "text": "Abolição do reflexo patelar."}, {"id": "D", "text": "Taquicardia."}]', 'C', 'A abolição (ausência) do reflexo patelar é o sinal mais precoce de intoxicação por sulfato de magnésio. Se não revertido, o quadro progride para depressão respiratória e parada cardíaca. O antídoto é o Gluconato de Cálcio.', 'FCC'),

-- Saúde da Criança
(476, 'Saúde da Criança', 'O Índice de Apgar, avaliado no 1º e 5º minuto de vida, NÃO inclui qual dos seguintes parâmetros?', '[{"id": "A", "text": "Frequência cardíaca."}, {"id": "B", "text": "Tônus muscular."}, {"id": "C", "text": "Temperatura corporal."}, {"id": "D", "text": "Cor da pele."}]', 'C', 'O Apgar avalia 5 parâmetros: Frequência Cardíaca, Esforço Respiratório, Tônus Muscular, Irritabilidade Reflexa e Cor. A temperatura é um cuidado vital, mas não faz parte do escore de Apgar.', 'Cesgranrio'),
(477, 'Saúde da Criança', 'O Teste do Coraçãozinho (triagem de cardiopatias congênitas críticas) é realizado através de:', '[{"id": "A", "text": "Ausculta cardíaca em quatro focos."}, {"id": "B", "text": "Eletrocardiograma (ECG) de 12 derivações."}, {"id": "C", "text": "Aferição da pressão arterial nos quatro membros."}, {"id": "D", "text": "Oximetria de pulso no membro superior direito e em um dos membros inferiores."}]', 'D', 'O Teste do Coraçãozinho consiste na aferição da saturação de oxigênio (SpO2) no membro superior direito (pré-ductal) e em um dos pés (pós-ductal). Um resultado positivo (SpO2 < 95% ou diferença > 3% entre os membros) indica a necessidade de investigação com ecocardiograma.', 'AOCP'),
(478, 'Saúde da Criança', 'Em relação ao ganho de peso do recém-nascido a termo e saudável, qual é a expectativa para o primeiro ano de vida?', '[{"id": "A", "text": "Dobrar o peso do nascimento aos 3 meses e triplicar aos 6 meses."}, {"id": "B", "text": "Manter o peso do nascimento na primeira semana e dobrar aos 12 meses."}, {"id": "C", "text": "Perder até 10% do peso na primeira semana, dobrar aos 5-6 meses e triplicar aos 12 meses."}, {"id": "D", "text": "Ganhar 1kg por mês durante todo o primeiro ano."}]', 'C', 'A regra geral é que o RN perde até 10% do peso na primeira semana, recupera até o 10º-14º dia, dobra o peso do nascimento por volta do 5º ao 6º mês e triplica com 1 ano de idade.', 'Vunesp'),
(479, 'Saúde da Criança', 'Qual das seguintes condições maternas é uma contraindicação absoluta para o aleitamento materno no Brasil?', '[{"id": "A", "text": "Hepatite B."}, {"id": "B", "text": "Tuberculose em tratamento."}, {"id": "C", "text": "Infecção pelo HIV."}, {"id": "D", "text": "Mastite."}]', 'C', 'No Brasil, as contraindicações absolutas e definitivas para amamentação são a infecção materna pelo HIV e pelo HTLV. Em outras condições, como Hepatite B (se o RN recebe vacina e imunoglobulina) ou Tuberculose (se a mãe está em tratamento), a amamentação é geralmente incentivada.', 'IBFC'),
(480, 'Saúde da Criança', 'Qual é o marco do desenvolvimento motor esperado para uma criança por volta dos 6 meses de idade?', '[{"id": "A", "text": "Sustentar a cabeça firmemente."}, {"id": "B", "text": "Andar com apoio."}, {"id": "C", "text": "Sentar-se sem apoio."}, {"id": "D", "text": "Formar a pinça com o polegar e o indicador."}]', 'C', 'O marco motor grosso esperado por volta dos 6 a 7 meses é a capacidade de sentar-se sem apoio. Sustentar a cabeça ocorre por volta dos 3 meses, e andar com apoio por volta dos 9-10 meses.', 'FGV'),

-- Biossegurança e CME
(481, 'Biossegurança e Controle de Infecção', 'Qual tipo de precaução deve ser adotado para um paciente com diagnóstico de Tuberculose Pulmonar Bacilífera?', '[{"id": "A", "text": "Precaução Padrão."}, {"id": "B", "text": "Precaução de Contato."}, {"id": "C", "text": "Precaução para Gotículas."}, {"id": "D", "text": "Precaução para Aerossóis."}]', 'D', 'A Tuberculose é transmitida por aerossóis (partículas < 5 micra que ficam suspensas no ar). Portanto, exige Precaução para Aerossóis, que inclui o uso de máscara N95/PFF2 pelo profissional e, idealmente, quarto com pressão negativa.', 'Cebraspe'),
(482, 'Biossegurança e Controle de Infecção', 'De acordo com a RDC 222/2018 da ANVISA, os resíduos do Grupo A (biológicos/infectantes) devem ser acondicionados em:', '[{"id": "A", "text": "Saco preto."}, {"id": "B", "text": "Saco branco leitoso."}, {"id": "C", "text": "Caixa amarela para perfurocortantes."}, {"id": "D", "text": "Saco laranja."}]', 'B', 'Os resíduos do Grupo A, que apresentam risco biológico, devem ser acondicionados em saco branco leitoso, identificado com o símbolo de risco biológico. O saco preto é para resíduo comum (Grupo D).', 'FCC'),
(483, 'Centro Cirúrgico', 'Um endoscópio flexível, que entra em contato com mucosas íntegras, é classificado, segundo Spaulding, como um artigo:', '[{"id": "A", "text": "Crítico, exigindo esterilização."}, {"id": "B", "text": "Semicrítico, exigindo desinfecção de alto nível."}, {"id": "C", "text": "Não crítico, exigindo apenas limpeza."}, {"id": "D", "text": "Descartável, não podendo ser reprocessado."}]', 'B', 'Artigos que entram em contato com mucosas íntegras são classificados como semicríticos. O processo mínimo exigido é a desinfecção de alto nível, que elimina micobactérias, fungos e vírus, mas não necessariamente todos os esporos bacterianos.', 'Vunesp'),
(484, 'Centro Cirúrgico', 'Qual é o indicador padrão-ouro utilizado para validar a eficácia de um ciclo de esterilização em autoclave a vapor?', '[{"id": "A", "text": "Indicador químico Classe 5 (integrador)."}, {"id": "B", "text": "Fita termossensível (indicador químico Classe 1)."}, {"id": "C", "text": "Indicador biológico com esporos de Geobacillus stearothermophilus."}, {"id": "D", "text": "Teste de Bowie-Dick."}]', 'C', 'O indicador biológico é o padrão-ouro, pois testa diretamente a capacidade do ciclo de matar os microrganismos mais resistentes (esporos). O Geobacillus stearothermophilus é o microrganismo de escolha para o vapor.', 'IBFC'),
(485, 'Biossegurança e Controle de Infecção', 'A NR-32 estabelece uma regra fundamental sobre o manejo de materiais perfurocortantes. Qual das seguintes práticas é expressamente VEDADA?', '[{"id": "A", "text": "O descarte de agulhas em caixas coletoras."}, {"id": "B", "text": "O reencape de agulhas após o uso."}, {"id": "C", "text": "O uso de agulhas com dispositivo de segurança."}, {"id": "D", "text": "O preenchimento do coletor até a linha pontilhada."}]', 'B', 'A NR-32 veda terminantemente o reencape e a desconexão manual de agulhas, pois estas são as principais causas de acidentes com perfurocortantes. O descarte deve ser imediato no coletor após o uso.', 'FGV'),

-- Fundamentos de Enfermagem
(486, 'Fundamentos de Enfermagem', 'A frequência respiratória de um adulto em repouso, considerada dentro da normalidade, é denominada:', '[{"id": "A", "text": "Taquipneia."}, {"id": "B", "text": "Bradipneia."}, {"id": "C", "text": "Eupneia."}, {"id": "D", "text": "Ortopneia."}]', 'C', 'Eupneia é o termo técnico para a respiração normal, sem esforço, com frequência e ritmo dentro dos padrões de normalidade (12 a 20 irpm em adultos).', 'AOCP'),
(487, 'Fundamentos de Enfermagem', 'Qual é o local de aplicação preferencial para injeções intramusculares de grande volume (acima de 3ml) em adultos?', '[{"id": "A", "text": "Músculo Deltoide."}, {"id": "B", "text": "Músculo Vasto Lateral."}, {"id": "C", "text": "Músculo Ventroglúteo."}, {"id": "D", "text": "Músculo Dorsoglúteo."}]', 'C', 'O músculo ventroglúteo é considerado o local mais seguro e preferencial para injeções IM em adultos, pois é livre de grandes vasos e nervos importantes (como o ciático), tem boa espessura muscular e pouca camada adiposa.', 'Cebraspe'),
(488, 'Fundamentos de Enfermagem', 'A Sistematização da Assistência de Enfermagem (SAE) é organizada em 5 etapas. Qual etapa é de competência privativa do Enfermeiro?', '[{"id": "A", "text": "Coleta de Dados."}, {"id": "B", "text": "Diagnóstico de Enfermagem."}, {"id": "C", "text": "Implementação."}, {"id": "D", "text": "Avaliação de Enfermagem."}]', 'B', 'Segundo a Resolução COFEN 358/2009, o Diagnóstico de Enfermagem, que é o julgamento clínico sobre as respostas do paciente, é uma atividade privativa do Enfermeiro e constitui a base para o planejamento do cuidado.', 'FCC'),
(489, 'Fundamentos de Enfermagem', 'Ao avaliar uma ferida, o enfermeiro observa um tecido vermelho vivo, úmido e com aspecto granular no leito da lesão. Esse tecido é denominado:', '[{"id": "A", "text": "Tecido de epitelização."}, {"id": "B", "text": "Esfacelo."}, {"id": "C", "text": "Tecido de granulação."}, {"id": "D", "text": "Escara."}]', 'C', 'O tecido de granulação é um tecido conjuntivo novo, altamente vascularizado, que se forma durante o processo de cicatrização. Sua presença é um sinal positivo de que a ferida está evoluindo bem.', 'Vunesp'),
(490, 'Fundamentos de Enfermagem', 'A administração de um medicamento na hora errada, mesmo que não cause dano ao paciente, é considerada um(a):', '[{"id": "A", "text": "Evento adverso."}, {"id": "B", "text": "Incidente sem dano."}, {"id": "C", "text": "Near miss (Quase erro)."}, {"id": "D", "text": "Condição de risco."}]', 'B', 'Um incidente é um evento que poderia ter resultado, ou resultou, em dano desnecessário. Se o erro ocorreu (medicamento na hora errada) mas não causou dano ao paciente, é classificado como um incidente sem dano. Um ''near miss'' é quando o erro é interceptado ANTES de atingir o paciente.', 'IBFC');