-- Pacote de 20 questões para equilibrar categorias com baixo volume
-- Foco: Saúde do Trabalhador, SAE, Saúde Mental, Farmacologia, Biossegurança

INSERT INTO public.questions (id, category, question, options, "correctAnswer", explanation, banca) VALUES
-- Saúde do Trabalhador
(531, 'Saúde do Trabalhador', 'A Norma Regulamentadora 32 (NR-32) veda o uso de adornos pelos trabalhadores em áreas de assistência. Qual o principal motivo para essa proibição?', '[{"id": "A", "text": "Evitar distrações durante os procedimentos."}, {"id": "B", "text": "Prevenir o risco de acidentes por agarramento em equipamentos."}, {"id": "C", "text": "Reduzir o risco de contaminação cruzada, pois adornos podem abrigar microrganismos."}, {"id": "D", "text": "Padronizar a aparência da equipe de saúde."}]', 'C', 'A principal justificativa para a proibição de adornos (anéis, pulseiras, relógios, etc.) é que eles dificultam a correta higienização das mãos e podem servir como reservatórios de microrganismos, aumentando o risco de infecção cruzada entre pacientes e profissionais.', 'FGV'),
(532, 'Saúde do Trabalhador', 'Após um acidente com material perfurocortante contaminado com sangue de paciente com HIV, qual é a conduta imediata e prioritária para o profissional acidentado?', '[{"id": "A", "text": "Lavar o local com água e sabão, sem esfregar, e comunicar a chefia e o CCIH."}, {"id": "B", "text": "Induzir sangramento no local da picada para expulsar o vírus."}, {"id": "C", "text": "Aplicar álcool 70% no local da ferida."}, {"id": "D", "text": "Procurar o serviço de emergência apenas se surgirem sintomas."}]', 'A', 'A conduta imediata é lavar abundantemente o local com água e sabão, sem provocar mais sangramento. Em seguida, o acidente deve ser comunicado imediatamente à chefia, ao SESMT e à CCIH para avaliação do risco e início da Profilaxia Pós-Exposição (PEP), se indicada, idealmente nas primeiras 2 horas.', 'Cebraspe'),
(533, 'Saúde do Trabalhador', 'De acordo com a RDC 222/2018, resíduos químicos perigosos, como medicamentos quimioterápicos, pertencem a qual grupo e devem ser acondicionados em qual tipo de recipiente?', '[{"id": "A", "text": "Grupo A, em saco branco leitoso."}, {"id": "B", "text": "Grupo B, em recipientes rígidos, estanques e identificados com o símbolo de risco químico."}, {"id": "C", "text": "Grupo D, em saco preto comum."}, {"id": "D", "text": "Grupo E, em caixa para perfurocortantes."}]', 'B', 'Os resíduos químicos (Grupo B) devem ser acondicionados em recipientes rígidos e identificados, que previnam vazamentos e sejam compatíveis com o produto químico. A cor laranja é frequentemente associada a resíduos quimioterápicos.', 'Vunesp'),
(534, 'Saúde do Trabalhador', 'A notificação de um acidente de trabalho que resulta em morte é de que tipo?', '[{"id": "A", "text": "Notificação semanal ao SINAN."}, {"id": "B", "text": "Notificação imediata (em até 24 horas) ao SINAN."}, {"id": "C", "text": "Notificação apenas à Previdência Social através da CAT."}, {"id": "D", "text": "Notificação mensal ao Ministério do Trabalho."}]', 'B', 'Acidentes de trabalho fatais, graves (com mutilação) ou que envolvam crianças e adolescentes são de notificação compulsória imediata, devendo ser comunicados em até 24 horas ao Sistema de Informação de Agravos de Notificação (SINAN).', 'IBFC'),

-- Sistematização da Assistência (SAE)
(535, 'Sistematização da Assistência (SAE)', 'A Teoria do Autocuidado, que define três sistemas de enfermagem (totalmente compensatório, parcialmente compensatório e de apoio-educação), foi desenvolvida por qual teórica?', '[{"id": "A", "text": "Wanda Horta."}, {"id": "B", "text": "Dorothea Orem."}, {"id": "C", "text": "Madeleine Leininger."}, {"id": "D", "text": "Hildegard Peplau."}]', 'B', 'Dorothea Orem é a autora da Teoria do Déficit do Autocuidado, que estrutura a assistência de enfermagem com base na capacidade do paciente de cuidar de si mesmo, definindo o nível de intervenção necessário.', 'FCC'),
(536, 'Sistematização da Assistência (SAE)', 'Qual a principal diferença entre um Diagnóstico de Enfermagem de Risco e um Diagnóstico com Foco no Problema (Real)?', '[{"id": "A", "text": "O diagnóstico de risco não possui etiologia (fatores relacionados)."}, {"id": "B", "text": "O diagnóstico de risco não possui características definidoras (sinais e sintomas), pois o problema ainda não ocorreu."}, {"id": "C", "text": "O diagnóstico de risco é privativo do enfermeiro, enquanto o real pode ser feito por toda a equipe."}, {"id": "D", "text": "O diagnóstico de risco utiliza a estrutura P.E.S., e o real não."}]', 'B', 'Um diagnóstico de risco descreve a vulnerabilidade a um problema de saúde. Ele é composto pelo problema e pelos fatores de risco, mas não possui características definidoras (sinais/sintomas), pois estes ainda não estão presentes.', 'Cesgranrio'),
(537, 'Sistematização da Assistência (SAE)', 'Ao planejar o cuidado para um paciente com múltiplos diagnósticos de enfermagem, o enfermeiro deve priorizá-los. Qual critério é o mais utilizado para essa priorização?', '[{"id": "A", "text": "A preferência do paciente."}, {"id": "B", "text": "A facilidade de resolução do problema."}, {"id": "C", "text": "A hierarquia das necessidades humanas básicas de Maslow."}, {"id": "D", "text": "A ordem em que os diagnósticos foram identificados."}]', 'C', 'A Pirâmide de Maslow é a ferramenta teórica mais utilizada para priorizar os cuidados. Necessidades fisiológicas (respiração, circulação, hidratação) e de segurança têm prioridade sobre necessidades sociais ou de autoestima.', 'AOCP'),
(538, 'Sistematização da Assistência (SAE)', 'A etapa de Avaliação do Processo de Enfermagem é melhor descrita como:', '[{"id": "A", "text": "Um processo final, realizado apenas na alta do paciente."}, {"id": "B", "text": "Um processo contínuo e sistemático de comparação dos resultados alcançados com os resultados esperados."}, {"id": "C", "text": "A checagem das intervenções realizadas no prontuário."}, {"id": "D", "text": "A coleta de novos dados para iniciar um novo processo."}]', 'B', 'A avaliação não é apenas um passo final, mas um processo contínuo que ocorre durante toda a assistência. O enfermeiro compara o estado atual do paciente com as metas definidas no planejamento para determinar a eficácia do plano e a necessidade de ajustes.', 'IBFC'),

-- Saúde Mental
(539, 'Saúde Mental', 'A Lei 10.216/2001 (Reforma Psiquiátrica) prevê três modalidades de internação. Qual delas exige uma determinação judicial?', '[{"id": "A", "text": "Internação Voluntária."}, {"id": "B", "text": "Internação Involuntária."}, {"id": "C", "text": "Internação Compulsória."}, {"id": "D", "text": "Internação Social."}]', 'C', 'A internação compulsória é aquela determinada pelo juiz, que leva em conta as condições de segurança do estabelecimento e do paciente. A internação involuntária ocorre a pedido de terceiro, sem o consentimento do paciente, e deve ser comunicada ao Ministério Público.', 'FGV'),
(540, 'Saúde Mental', 'Qual é o papel principal do Centro de Atenção Psicossocial (CAPS) na Rede de Atenção Psicossocial (RAPS)?', '[{"id": "A", "text": "Realizar internações de longa permanência."}, {"id": "B", "text": "Ser o ordenador do cuidado e da rede, oferecendo atendimento intensivo, semi-intensivo e não intensivo."}, {"id": "C", "text": "Atender exclusivamente emergências psiquiátricas."}, {"id": "D", "text": "Fornecer apenas consultas médicas especializadas."}]', 'B', 'O CAPS é o serviço estratégico e ordenador da RAPS. Ele organiza a rede, articula os diferentes pontos de atenção e oferece cuidado territorial e multiprofissional, conforme a intensidade necessária para cada caso, visando a reinserção social.', 'Cebraspe'),
(541, 'Saúde Mental', 'O Projeto Terapêutico Singular (PTS) é uma ferramenta fundamental no cuidado em saúde mental. Sua principal característica é:', '[{"id": "A", "text": "Ser um protocolo padrão aplicado a todos os pacientes com o mesmo diagnóstico."}, {"id": "B", "text": "Ser um plano de cuidados construído coletivamente pela equipe multiprofissional e, sempre que possível, com o usuário e sua família."}, {"id": "C", "text": "Ser um plano focado exclusivamente na prescrição de psicofármacos."}, {"id": "D", "text": "Ser um documento de uso exclusivo do médico psiquiatra."}]', 'B', 'O PTS é uma estratégia de cuidado individualizada e construída de forma coletiva, que vai além do diagnóstico e considera a singularidade do sujeito, seu contexto de vida e suas necessidades. É uma ferramenta de corresponsabilização.', 'Vunesp'),
(542, 'Saúde Mental', 'Um paciente em uso de Haloperidol apresenta tremores, rigidez muscular, marcha arrastada e face inexpressiva. Esses sinais são característicos de qual efeito adverso?', '[{"id": "A", "text": "Síndrome Neuroléptica Maligna."}, {"id": "B", "text": "Sintomas extrapiramidais (parkinsonismo)."}, {"id": "C", "text": "Acatisia."}, {"id": "D", "text": "Crise hipertensiva."}]', 'B', 'Os sintomas descritos (rigidez, tremor de repouso, bradicinesia) são característicos do parkinsonismo secundário, um dos principais efeitos extrapiramidais dos antipsicóticos de primeira geração (típicos), como o Haloperidol, devido ao bloqueio de receptores de dopamina.', 'FCC'),

-- Biossegurança e Controle de Infecção
(543, 'Biossegurança e Controle de Infecção', 'Qual dos 5 Momentos para Higienização das Mãos da OMS visa proteger o profissional de se contaminar com fluidos corporais do paciente?', '[{"id": "A", "text": "Momento 1 (Antes do contato com o paciente)."}, {"id": "B", "text": "Momento 2 (Antes de procedimento limpo/asséptico)."}, {"id": "C", "text": "Momento 3 (Após risco de exposição a fluidos corporais)."}, {"id": "D", "text": "Momento 5 (Após contato com áreas próximas ao paciente)."}]', 'C', 'O Momento 3 ocorre imediatamente após a remoção das luvas ou qualquer situação com risco de exposição a fluidos (sangue, urina, secreções), e tem como objetivo principal proteger o profissional e o ambiente de saúde.', 'IBFC'),
(544, 'Biossegurança e Controle de Infecção', 'A limpeza de uma superfície contaminada com matéria orgânica (sangue) deve ser precedida por qual ação?', '[{"id": "A", "text": "Aplicação de desinfetante diretamente sobre a matéria orgânica."}, {"id": "B", "text": "Remoção da matéria orgânica com papel toalha ou compressa."}, {"id": "C", "text": "Aplicação de álcool 70% para fixar a sujidade."}, {"id": "D", "text": "Aguardar a secagem natural da matéria orgânica."}]', 'B', 'A matéria orgânica inativa a maioria dos desinfetantes. Portanto, a primeira etapa é sempre a remoção mecânica da sujidade com um papel ou pano, para depois realizar a limpeza com água e sabão e, por fim, a desinfecção.', 'Cesgranrio'),
(545, 'Biossegurança e Controle de Infecção', 'Um paciente com Varicela (catapora) disseminada requer qual tipo de precaução?', '[{"id": "A", "text": "Apenas Precaução para Aerossóis."}, {"id": "B", "text": "Apenas Precaução de Contato."}, {"id": "C", "text": "Precaução para Aerossóis e Precaução de Contato."}, {"id": "D", "text": "Precaução para Gotículas."}]', 'C', 'A Varicela é transmitida tanto por aerossóis (partículas respiratórias) quanto por contato direto com as lesões de pele. Portanto, exige a associação das duas precauções: quarto com pressão negativa, máscara N95, luvas e avental.', 'AOCP'),
(546, 'Biossegurança e Controle de Infecção', 'Qual é a principal função da Comissão de Controle de Infecção Hospitalar (CCIH)?', '[{"id": "A", "text": "Punir os profissionais que não higienizam as mãos."}, {"id": "B", "text": "Realizar a compra de todos os antibióticos do hospital."}, {"id": "C", "text": "Elaborar, implementar e supervisionar um programa de controle de infecções, incluindo vigilância epidemiológica e normas."}, {"id": "D", "text": "Realizar a limpeza terminal de todas as unidades de internação."}]', 'C', 'A CCIH é um órgão de assessoria à direção do hospital, responsável por desenvolver um programa abrangente de prevenção e controle das infecções relacionadas à assistência à saúde (IRAS), que inclui vigilância, elaboração de normas, educação e investigação de surtos.', 'IBFC'),

-- Farmacologia
(547, 'Farmacologia', 'Qual exame laboratorial é utilizado para monitorar o efeito do anticoagulante oral Varfarina (Marevan)?', '[{"id": "A", "text": "Tempo de Tromboplastina Parcial Ativada (TTPa)."}, {"id": "B", "text": "Contagem de Plaquetas."}, {"id": "C", "text": "Tempo de Protrombina (TP) / Relação Normatizada Internacional (RNI ou INR)."}, {"id": "D", "text": "Dímero-D."}]', 'C', 'A Varfarina age na via extrínseca da coagulação, inibindo fatores dependentes de Vitamina K. O TP/RNI é o exame que avalia essa via e é usado para ajustar a dose, mantendo o RNI na faixa terapêutica (geralmente 2,0-3,0). O TTPa monitora a Heparina.', 'FGV'),
(548, 'Farmacologia', 'A ''Síndrome do Homem Vermelho'' (rubor facial e de tronco, prurido, hipotensão) é uma reação adversa associada à infusão rápida de qual antibiótico?', '[{"id": "A", "text": "Ceftriaxona."}, {"id": "B", "text": "Vancomicina."}, {"id": "C", "text": "Penicilina Cristalina."}, {"id": "D", "text": "Meropenem."}]', 'B', 'A Síndrome do Homem Vermelho é uma reação de hipersensibilidade não alérgica causada pela liberação de histamina devido à infusão rápida de Vancomicina. Para preveni-la, a infusão deve ser lenta, em no mínimo 60 minutos.', 'Cebraspe'),
(549, 'Farmacologia', 'A Noradrenalina, um potente vasopressor, deve ser administrada preferencialmente por qual via e em qual local?', '[{"id": "A", "text": "Via intramuscular, no músculo deltoide."}, {"id": "B", "text": "Via subcutânea, no abdome."}, {"id": "C", "text": "Via endovenosa, em acesso venoso central."}, {"id": "D", "text": "Via endovenosa, em qualquer acesso periférico."}]', 'C', 'Drogas vasoativas como a Noradrenalina são extremamente vesicantes e podem causar necrose tecidual grave se extravasarem. Por isso, a via de administração de escolha é um acesso venoso central, cuja ponta está em uma veia de grande calibre (ex: Veia Cava Superior).', 'Vunesp'),
(550, 'Farmacologia', 'Qual é o fármaco de escolha para reverter uma depressão respiratória causada por superdosagem de Benzodiazepínicos (ex: Diazepam, Midazolam)?', '[{"id": "A", "text": "Naloxona."}, {"id": "B", "text": "Atropina."}, {"id": "C", "text": "Flumazenil."}, {"id": "D", "text": "Adrenalina."}]', 'C', 'O Flumazenil (Lanexat) é um antagonista específico dos receptores benzodiazepínicos, revertendo seus efeitos sedativos e respiratórios. A Naloxona é o antídoto para os opioides (Morfina, Fentanil).', 'FCC');