-- Pacote de 20 questões para reforçar categorias com baixo volume
-- Foco: Imunização, Centro Cirúrgico, Saúde do Adulto, Saúde do Idoso

INSERT INTO public.questions (id, category, question, options, "correctAnswer", explanation, banca) VALUES
-- Imunização
(551, 'Imunização', 'Qual é a via de administração correta da vacina BCG e qual a evolução esperada da lesão vacinal?', '[{"id": "A", "text": "Subcutânea; formação de pápula imediata que desaparece em 24h."}, {"id": "B", "text": "Intramuscular; dor local e febre baixa."}, {"id": "C", "text": "Intradérmica; mácula -> pápula -> pústula -> úlcera -> cicatriz."}, {"id": "D", "text": "Oral; sem reação local."}]', 'C', 'A vacina BCG é administrada por via intradérmica, preferencialmente no músculo deltoide direito. A evolução normal da lesão é uma mácula avermelhada em 2 semanas, que evolui para pápula, pústula, ulcera e, finalmente, deixa uma cicatriz característica após 6-12 semanas.', 'Vunesp'),
(552, 'Imunização', 'A vacina contra o Rotavírus Humano (VORH) tem um calendário rigoroso. Qual é a idade máxima para a administração da primeira dose?', '[{"id": "A", "text": "3 meses e 15 dias."}, {"id": "B", "text": "5 meses e 15 dias."}, {"id": "C", "text": "7 meses e 29 dias."}, {"id": "D", "text": "1 ano de idade."}]', 'A', 'A primeira dose da vacina contra o Rotavírus deve ser administrada a partir de 1 mês e 15 dias até, no máximo, 3 meses e 15 dias. A segunda dose tem como idade máxima 7 meses e 29 dias. Esses limites são para reduzir o risco de invaginação intestinal.', 'Cebraspe'),
(553, 'Imunização', 'Em caso de interrupção do fornecimento de energia elétrica na sala de vacinas, qual a primeira ação a ser tomada pelo profissional de enfermagem?', '[{"id": "A", "text": "Descartar todas as vacinas imediatamente."}, {"id": "B", "text": "Anotar o horário da interrupção e a temperatura atual, e vedar a porta da geladeira."}, {"id": "C", "text": "Transferir todas as vacinas para uma caixa térmica com gelo comum."}, {"id": "D", "text": "Abrir a geladeira para verificar se as vacinas ainda estão boas."}]', 'B', 'A primeira conduta é registrar o horário e a temperatura, lacrar a porta do refrigerador com fita adesiva e comunicar a instância superior. Um refrigerador bem vedado pode manter a temperatura por algumas horas. A abertura da porta deve ser evitada ao máximo.', 'IBFC'),
(554, 'Imunização', 'Qual a composição da vacina Pentavalente oferecida no PNI e quais doenças ela previne?', '[{"id": "A", "text": "Sarampo, Caxumba, Rubéola, Varicela e Febre Amarela."}, {"id": "B", "text": "Difteria, Tétano, Coqueluche, Haemophilus influenzae tipo b e Hepatite B."}, {"id": "C", "text": "Poliomielite, Sarampo, Rubéola, Caxumba e Hepatite A."}, {"id": "D", "text": "Difteria, Tétano, Coqueluche, Poliomielite e Haemophilus influenzae tipo b."}]', 'B', 'A vacina Pentavalente combina em uma única injeção a proteção contra Difteria, Tétano, Coqueluche (Pertussis), infecções por Haemophilus influenzae tipo b (como meningite) e Hepatite B.', 'FCC'),
(555, 'Imunização', 'A vacina contra a Influenza (gripe) é ofertada anualmente. Por que essa vacina precisa ser repetida todos os anos?', '[{"id": "A", "text": "Porque a imunidade dura apenas 12 meses."}, {"id": "B", "text": "Porque os vírus da gripe sofrem mutações constantes, exigindo uma nova formulação da vacina a cada ano."}, {"id": "C", "text": "Para garantir que toda a população seja vacinada."}, {"id": "D", "text": "Porque a vacina é produzida com vírus vivo e precisa de reforço."}]', 'B', 'Os vírus Influenza têm uma alta taxa de mutação antigênica (drift e shift antigênico). Por isso, a Organização Mundial da Saúde (OMS) monitora as cepas circulantes e recomenda uma nova composição para a vacina a cada ano, para garantir a proteção contra as variantes mais prováveis de causar a epidemia sazonal.', 'AOCP'),

-- Centro Cirúrgico
(556, 'Centro Cirúrgico', 'Qual é a principal diferença entre a raquianestesia e a anestesia peridural?', '[{"id": "A", "text": "A raquianestesia é geral e a peridural é local."}, {"id": "B", "text": "Na raquianestesia o anestésico é injetado no espaço subaracnóideo (no líquor), enquanto na peridural é no espaço peridural."}, {"id": "C", "text": "A peridural tem início de ação mais rápido que a raquianestesia."}, {"id": "D", "text": "A raquianestesia permite o uso de cateter para doses contínuas."}]', 'B', 'A diferença fundamental é o local da injeção. A raquianestesia perfura a dura-máter e injeta o anestésico diretamente no líquido cefalorraquidiano, tendo um bloqueio mais rápido e denso. A peridural deposita o anestésico fora da dura-máter, permitindo a passagem de um cateter.', 'Cesgranrio'),
(557, 'Centro Cirúrgico', 'A contagem de compressas, gazes e instrumentais cirúrgicos é um passo crucial para a segurança do paciente. De quem é a responsabilidade por essa contagem?', '[{"id": "A", "text": "Exclusivamente do cirurgião."}, {"id": "B", "text": "Exclusivamente do anestesista."}, {"id": "C", "text": "Do instrumentador cirúrgico e do circulante de sala, em voz alta e de forma padronizada."}, {"id": "D", "text": "Apenas do circulante de sala."}]', 'C', 'A contagem é uma responsabilidade compartilhada, geralmente entre o instrumentador (que controla o material na mesa) e o circulante de sala (que controla o material fora da mesa). A contagem deve ser feita em voz alta em momentos-chave: antes do início, antes do fechamento de cavidades e no final da cirurgia.', 'IBFC'),
(558, 'Centro Cirúrgico', 'Qual é o agente antisséptico mais recomendado para o preparo da pele (antissepsia cirúrgica) devido à sua ação residual e amplo espectro?', '[{"id": "A", "text": "Álcool 70%."}, {"id": "B", "text": "PVPI (Iodopovidona) degermante."}, {"id": "C", "text": "Clorexidina alcoólica 0,5% ou 2%."}, {"id": "D", "text": "Água e sabão."}]', 'C', 'A Clorexidina alcoólica é considerada o padrão-ouro para antissepsia cirúrgica da pele, pois combina a ação rápida do álcool com a ação residual (permanece ativa na pele por horas) da clorexidina, oferecendo uma proteção mais prolongada contra infecção de sítio cirúrgico.', 'FGV'),
(559, 'Centro Cirúrgico', 'Durante o posicionamento do paciente em decúbito lateral para uma cirurgia, qual cuidado é essencial para prevenir lesões?', '[{"id": "A", "text": "Manter os braços do paciente ao longo do corpo."}, {"id": "B", "text": "Colocar um coxim entre os joelhos e proteger o maléolo inferior."}, {"id": "C", "text": "Elevar a cabeceira da mesa em 90 graus."}, {"id": "D", "text": "Não utilizar coxins para manter o alinhamento da coluna."}]', 'B', 'No decúbito lateral, é fundamental proteger as proeminências ósseas. Um coxim (travesseiro) entre os joelhos evita a compressão de nervos e vasos, e a proteção do maléolo do membro inferior (que fica em contato com a mesa) previne lesões por pressão.', 'Vunesp'),
(560, 'Centro Cirúrgico', 'O que é o Índice de Aldrete e Kroulik e qual pontuação mínima geralmente indica condições de alta da SRPA?', '[{"id": "A", "text": "Escala de dor; pontuação < 3."}, {"id": "B", "text": "Escala de risco de queda; pontuação > 45."}, {"id": "C", "text": "Escala de recuperação pós-anestésica; pontuação ≥ 9."}, {"id": "D", "text": "Escala de nível de sedação; pontuação 0."}]', 'C', 'O Índice de Aldrete e Kroulik avalia cinco parâmetros (Atividade, Respiração, Circulação, Consciência e Saturação de O2), com nota de 0 a 2 cada. Uma pontuação total igual ou superior a 9 geralmente indica que o paciente tem condições seguras para receber alta da Sala de Recuperação Pós-Anestésica.', 'Cebraspe'),

-- Saúde do Adulto
(561, 'Saúde do Adulto', 'Qual é o principal fator de risco modificável para o desenvolvimento da Doença Pulmonar Obstrutiva Crônica (DPOC)?', '[{"id": "A", "text": "Poluição do ar."}, {"id": "B", "text": "Exposição ocupacional a poeiras."}, {"id": "C", "text": "Tabagismo."}, {"id": "D", "text": "Deficiência de alfa-1-antitripsina."}]', 'C', 'O tabagismo é, de longe, o principal fator de risco para a DPOC, sendo responsável por cerca de 80-90% dos casos. A cessação do tabagismo é a única medida capaz de retardar a progressão da doença.', 'FCC'),
(562, 'Saúde do Adulto', 'Qual é a principal causa de Doença Renal Crônica (DRC) no Brasil e no mundo?', '[{"id": "A", "text": "Hipertensão Arterial Sistêmica (HAS)."}, {"id": "B", "text": "Diabetes Mellitus (DM)."}, {"id": "C", "text": "Doenças glomerulares primárias."}, {"id": "D", "text": "Infecções urinárias de repetição."}]', 'B', 'O Diabetes Mellitus é a principal causa de DRC, seguido de perto pela Hipertensão Arterial. O controle inadequado da glicemia e da pressão arterial ao longo dos anos leva a danos progressivos e irreversíveis nos glomérulos renais.', 'IBFC'),
(563, 'Saúde do Adulto', 'Qual é a principal orientação de enfermagem na alta hospitalar para um paciente com Insuficiência Cardíaca (IC)?', '[{"id": "A", "text": "Realizar exercícios físicos de alta intensidade diariamente."}, {"id": "B", "text": "Pesar-se diariamente em jejum e monitorar o surgimento de edema."}, {"id": "C", "text": "Aumentar a ingestão de sal para manter a pressão arterial."}, {"id": "D", "text": "Suspender os diuréticos se a urina estiver clara."}]', 'B', 'O controle de peso diário é a medida mais sensível para detectar a retenção hídrica precocemente, um sinal de descompensação da IC. Ganhos de peso rápidos (ex: > 1-2 kg em 24h) devem ser comunicados à equipe de saúde.', 'AOCP'),
(564, 'Saúde do Adulto', 'O tratamento da Hanseníase é feito com Poliquimioterapia (PQT). Qual é a principal diferença no esquema terapêutico entre as formas Paucibacilar (PB) e Multibacilar (MB)?', '[{"id": "A", "text": "A forma PB não utiliza Rifampicina."}, {"id": "B", "text": "A forma MB utiliza um medicamento a mais (Clofazimina) e tem duração maior (12 meses)."}, {"id": "C", "text": "A forma MB é tratada com apenas um medicamento."}, {"id": "D", "text": "A forma PB tem tratamento mais longo que a MB."}]', 'B', 'O esquema para Paucibacilar dura 6 meses (Rifampicina + Dapsona). O esquema para Multibacilar dura 12 meses e adiciona a Clofazimina ao esquema (Rifampicina + Dapsona + Clofazimina), para combater a maior carga bacilar.', 'Cesgranrio'),
(565, 'Saúde do Adulto', 'Qual é a característica que melhor diferencia um Acidente Vascular Cerebral (AVC) Hemorrágico de um Isquêmico na apresentação clínica inicial?', '[{"id": "A", "text": "O AVC hemorrágico sempre causa perda de consciência, e o isquêmico não."}, {"id": "B", "text": "O AVC isquêmico sempre apresenta desvio de rima labial."}, {"id": "C", "text": "Cefaleia súbita e intensa (''pior dor de cabeça da vida'') e vômitos são mais comuns no AVC hemorrágico."}, {"id": "D", "text": "Apenas o AVC isquêmico causa déficits motores focais."}]', 'C', 'Embora os sintomas possam se sobrepor, o AVC hemorrágico está mais associado a sinais de irritação meníngea e aumento da pressão intracraniana, como cefaleia súbita e excruciante, náuseas, vômitos e rebaixamento do nível de consciência. No entanto, a confirmação só é possível com a Tomografia de Crânio.', 'FGV'),

-- Saúde do Idoso
(566, 'Saúde do Idoso', 'Qual é a principal diferença clínica entre Delirium e Demência?', '[{"id": "A", "text": "Delirium é crônico e progressivo, enquanto Demência é aguda e reversível."}, {"id": "B", "text": "Delirium tem início agudo e curso flutuante, enquanto Demência tem início insidioso e curso progressivo."}, {"id": "C", "text": "Apenas a Demência causa alterações de memória."}, {"id": "D", "text": "Apenas o Delirium está associado a alucinações."}]', 'B', 'A principal característica do Delirium é o início súbito (horas a dias) e a flutuação do quadro ao longo do dia. A Demência, por outro lado, tem um início lento e gradual (meses a anos) e uma progressão mais estável.', 'Cebraspe'),
(567, 'Saúde do Idoso', 'O uso de cinco ou mais medicamentos diferentes por um paciente idoso é definido como:', '[{"id": "A", "text": "Iatrogenia."}, {"id": "B", "text": "Polifarmácia."}, {"id": "C", "text": "Interação medicamentosa."}, {"id": "D", "text": "Reação adversa."}]', 'B', 'Polifarmácia é o termo técnico para o uso concomitante de múltiplos medicamentos (geralmente 5 ou mais). É um fator de risco importante para iatrogenia, reações adversas e interações medicamentosas em idosos.', 'Vunesp'),
(568, 'Saúde do Idoso', 'Qual escala é comumente utilizada para avaliar a capacidade do idoso de realizar Atividades Instrumentais de Vida Diária (AIVD)?', '[{"id": "A", "text": "Escala de Katz."}, {"id": "B", "text": "Escala de Braden."}, {"id": "C", "text": "Escala de Lawton-Brody."}, {"id": "D", "text": "Mini Exame do Estado Mental (MEEM)."}]', 'C', 'A Escala de Lawton-Brody avalia atividades mais complexas que exigem maior função cognitiva, como usar o telefone, gerenciar finanças, usar transporte e preparar refeições. A Escala de Katz avalia as Atividades Básicas de Vida Diária (ABVD).', 'FCC'),
(569, 'Saúde do Idoso', 'Ao se comunicar com um idoso com presbiacusia (perda auditiva relacionada à idade), qual técnica é mais eficaz?', '[{"id": "A", "text": "Falar muito alto (gritar) diretamente no ouvido do paciente."}, {"id": "B", "text": "Falar de frente para o paciente, de forma clara, em um tom de voz mais grave."}, {"id": "C", "text": "Falar rapidamente para não cansar o paciente."}, {"id": "D", "text": "Usar apenas linguagem escrita para garantir a compreensão."}]', 'B', 'A presbiacusia afeta principalmente os sons de alta frequência (agudos). Falar em um tom mais grave, de forma clara, pausada e de frente para o paciente (permitindo a leitura labial) facilita muito a comunicação. Gritar distorce o som e é ineficaz.', 'IBFC'),
(570, 'Saúde do Idoso', 'Qual das seguintes opções é considerada um fator de risco intrínseco para quedas em idosos?', '[{"id": "A", "text": "Tapetes soltos em casa."}, {"id": "B", "text": "Iluminação inadequada."}, {"id": "C", "text": "Uso de múltiplos medicamentos (polifarmácia)."}, {"id": "D", "text": "Calçados inadequados."}]', 'C', 'Fatores de risco intrínsecos são aqueles relacionados às condições do próprio indivíduo (doenças, alterações fisiológicas, uso de medicamentos). Fatores extrínsecos são os relacionados ao ambiente. A polifarmácia pode causar tontura, hipotensão postural e sonolência, aumentando significativamente o risco de queda.', 'AOCP');