-- Pacote de 20 questões para reforçar categorias com baixo volume
-- Foco: Saúde do Idoso, Saúde do Adulto, Centro Cirúrgico, Farmacologia, Imunização

INSERT INTO public.questions (id, category, question, options, "correctAnswer", explanation, banca) VALUES
-- Saúde do Idoso
(511, 'Saúde do Idoso', 'De acordo com o Estatuto do Idoso (Lei 10.741/2003), é assegurado ao idoso internado ou em observação o direito a:', '[{"id": "A", "text": "Acompanhante apenas durante o dia."}, {"id": "B", "text": "Acompanhante em tempo integral, a critério da equipe de saúde."}, {"id": "C", "text": "Acompanhante em tempo integral, devendo o órgão de saúde proporcionar as condições adequadas para sua permanência."}, {"id": "D", "text": "Acompanhante apenas se o idoso tiver mais de 80 anos."}]', 'C', 'O Art. 16 do Estatuto do Idoso garante ao idoso internado o direito a acompanhante em período integral, sendo obrigação do hospital garantir as condições para a permanência desse acompanhante.', 'FGV'),
(512, 'Saúde do Idoso', 'Qual das seguintes condições é caracterizada por um distúrbio agudo e flutuante da atenção e cognição, geralmente secundário a uma causa clínica subjacente (infecção, distúrbio metabólico)?', '[{"id": "A", "text": "Demência."}, {"id": "B", "text": "Depressão."}, {"id": "C", "text": "Delirium."}, {"id": "D", "text": "Ansiedade."}]', 'C', 'Delirium (ou estado confusional agudo) é uma síndrome de início agudo e curso flutuante, caracterizada por desatenção e alteração do nível de consciência. É uma emergência médica e frequentemente precipitada por infecções, medicamentos ou distúrbios hidroeletrolíticos em idosos.', 'Cebraspe'),
(513, 'Saúde do Idoso', 'Na prevenção de quedas em idosos no ambiente hospitalar, qual das seguintes medidas é a mais importante?', '[{"id": "A", "text": "Manter o paciente sedado para evitar que ele se levante."}, {"id": "B", "text": "Manter as grades do leito sempre elevadas e orientar sobre o uso da campainha."}, {"id": "C", "text": "Deixar o quarto com pouca iluminação para não incomodar o paciente."}, {"id": "D", "text": "Restringir a deambulação do paciente fora do leito."}]', 'B', 'Manter as grades elevadas, o leito na posição mais baixa, o ambiente bem iluminado, os objetos de uso pessoal ao alcance e orientar o paciente e a família sobre a importância de chamar a enfermagem para auxílio são medidas fundamentais na prevenção de quedas.', 'Vunesp'),
(514, 'Saúde do Idoso', 'O envelhecimento fisiológico causa diversas alterações no organismo. Qual alteração renal é comum e impacta a dosagem de medicamentos em idosos?', '[{"id": "A", "text": "Aumento da Taxa de Filtração Glomerular (TFG)."}, {"id": "B", "text": "Diminuição da Taxa de Filtração Glomerular (TFG)."}, {"id": "C", "text": "Aumento da capacidade de concentração da urina."}, {"id": "D", "text": "Diminuição da creatinina sérica."}]', 'B', 'Com o envelhecimento, ocorre uma redução fisiológica do número de néfrons e do fluxo sanguíneo renal, levando a uma diminuição progressiva da Taxa de Filtração Glomerular. Isso reduz a capacidade de excretar medicamentos, aumentando o risco de toxicidade.', 'IBFC'),

-- Saúde do Adulto (Clínica Médica)
(515, 'Saúde do Adulto', 'Qual é o cuidado de enfermagem prioritário na avaliação de uma fístula arteriovenosa (FAV) para hemodiálise?', '[{"id": "A", "text": "Verificar a temperatura e a coloração do membro."}, {"id": "B", "text": "Aferir a pressão arterial no membro da fístula."}, {"id": "C", "text": "Verificar a presença de frêmito (vibração) e sopro (ausculta)."}, {"id": "D", "text": "Realizar curativo oclusivo diário no local da fístula."}]', 'C', 'A presença de frêmito (sensação vibratória à palpação) e sopro (som de fluxo turbilhonado à ausculta) são os principais sinais de perviedade e bom funcionamento da fístula. A ausência desses sinais indica trombose e é uma emergência.', 'FCC'),
(516, 'Saúde do Adulto', 'Um paciente com Doença Pulmonar Obstrutiva Crônica (DPOC) grave, retentor crônico de CO2, apresenta dispneia e SpO2 de 86%. Qual a conduta inicial em relação à oxigenoterapia?', '[{"id": "A", "text": "Administrar O2 em alto fluxo (10-15 L/min) com máscara não reinalante para atingir SpO2 de 100%."}, {"id": "B", "text": "Não administrar oxigênio, pois pode inibir o drive respiratório."}, {"id": "C", "text": "Administrar O2 em baixo fluxo (1-2 L/min) via cateter nasal, com alvo de SpO2 entre 88-92%."}, {"id": "D", "text": "Preparar para intubação orotraqueal imediata."}]', 'C', 'Em pacientes com DPOC retentores crônicos de CO2, o principal estímulo para a respiração é a hipoxemia. Oxigênio em excesso pode diminuir esse estímulo e levar à narcose por CO2. Portanto, a oxigenoterapia deve ser titulada para um alvo de saturação mais baixo (88-92%).', 'Cesgranrio'),
(517, 'Saúde do Adulto', 'Qual dos seguintes sinais é mais característico de uma descompensação de Insuficiência Cardíaca (IC) Esquerda?', '[{"id": "A", "text": "Edema de membros inferiores e ascite."}, {"id": "B", "text": "Estase de jugular e hepatomegalia."}, {"id": "C", "text": "Ortopneia e estertores crepitantes na ausculta pulmonar."}, {"id": "D", "text": "Pulsos periféricos finos e pele fria."}]', 'C', 'A falência do ventrículo esquerdo leva ao acúmulo de sangue nos pulmões (congestão pulmonar), causando dispneia, ortopneia (falta de ar ao deitar) e estertores crepitantes (som de líquido nos alvéolos). Os outros sinais são mais característicos da IC Direita.', 'AOCP'),
(518, 'Saúde do Adulto', 'Na fase aguda de um AVC isquêmico, qual é um cuidado de enfermagem crucial para prevenir complicações?', '[{"id": "A", "text": "Manter o paciente em repouso absoluto no leito por 72 horas."}, {"id": "B", "text": "Realizar controle rigoroso da glicemia capilar, evitando hipo e hiperglicemia."}, {"id": "C", "text": "Administrar dieta líquida via oral imediatamente para garantir a nutrição."}, {"id": "D", "text": "Manter a cabeceira do leito em 0 grau para melhorar a perfusão cerebral."}]', 'B', 'Tanto a hipoglicemia quanto a hiperglicemia são deletérias para o cérebro isquêmico, aumentando a área de penumbra e piorando o prognóstico. O controle glicêmico rigoroso é um pilar do cuidado na fase aguda do AVC.', 'IBFC'),

-- Centro Cirúrgico e CME
(519, 'Centro Cirúrgico', 'Uma cirurgia de colecistectomia videolaparoscópica eletiva, sem inflamação aguda e sem quebra de técnica asséptica, é classificada quanto ao potencial de contaminação como:', '[{"id": "A", "text": "Limpa."}, {"id": "B", "text": "Potencialmente Contaminada."}, {"id": "C", "text": "Contaminada."}, {"id": "D", "text": "Infectada."}]', 'B', 'Cirurgias que envolvem a abertura de tratos digestório, respiratório ou geniturinário em condições controladas e sem contaminação grosseira são classificadas como potencialmente contaminadas, pois há um risco inerente de contaminação pela flora local.', 'FGV'),
(520, 'Centro Cirúrgico', 'Qual posição cirúrgica é mais associada ao risco de lesão do nervo fibular, causando ''pé caído'' no pós-operatório?', '[{"id": "A", "text": "Trendelenburg."}, {"id": "B", "text": "Litotomia."}, {"id": "C", "text": "Decúbito ventral (prona)."}, {"id": "D", "text": "Decúbito lateral."}]', 'B', 'A posição de litotomia (ginecológica), com as pernas apoiadas em perneiras, pode causar compressão do nervo fibular comum na região da cabeça da fíbula (lateral do joelho), levando à paralisia do movimento de dorsiflexão do pé.', 'Cebraspe'),
(521, 'Centro Cirúrgico', 'Na monitorização da esterilização, qual a função do indicador químico Classe 1 (fita zebrada)?', '[{"id": "A", "text": "Garantir que o material está estéril."}, {"id": "B", "text": "Indicar que o pacote passou pelo processo de esterilização, diferenciando-o dos não processados."}, {"id": "C", "text": "Validar a morte de todos os microrganismos, incluindo esporos."}, {"id": "D", "text": "Verificar a eficácia da remoção de ar da autoclave."}]', 'B', 'O indicador químico Classe 1, como a fita zebrada, é um indicador de processo. Ele muda de cor quando exposto a uma determinada temperatura, servindo apenas para diferenciar visualmente os pacotes que passaram pelo processo daqueles que não passaram. Ele não garante a esterilidade.', 'Vunesp'),
(522, 'Centro Cirúrgico', 'Qual é a complicação mais comum e imediata na Sala de Recuperação Pós-Anestésica (SRPA)?', '[{"id": "A", "text": "Infecção de sítio cirúrgico."}, {"id": "B", "text": "Trombose Venosa Profunda (TVP)."}, {"id": "C", "text": "Obstrução de vias aéreas e hipoventilação."}, {"id": "D", "text": "Íleo paralítico."}]', 'C', 'Devido ao efeito residual dos anestésicos e relaxantes musculares, a complicação mais frequente e temida no pós-operatório imediato é a obstrução da via aérea (pela queda da língua) e a hipoventilação, que podem levar à hipóxia. Por isso, o monitoramento respiratório é intensivo na SRPA.', 'FCC'),

-- Farmacologia
(523, 'Farmacologia', 'O estudo de ''o que o corpo faz com o fármaco'', envolvendo os processos de absorção, distribuição, metabolismo e excreção, é denominado:', '[{"id": "A", "text": "Farmacodinâmica."}, {"id": "B", "text": "Farmacocinética."}, {"id": "C", "text": "Farmacogenética."}, {"id": "D", "text": "Farmacotécnica."}]', 'B', 'Farmacocinética é o estudo do movimento do fármaco no organismo (LADME). Farmacodinâmica é o estudo do efeito do fármaco no organismo (mecanismo de ação).', 'IBFC'),
(524, 'Farmacologia', 'Qual é o antídoto utilizado para reverter os efeitos de uma superdosagem de Heparina não fracionada?', '[{"id": "A", "text": "Vitamina K (Fitomenadiona)."}, {"id": "B", "text": "Naloxona."}, {"id": "C", "text": "Flumazenil."}, {"id": "D", "text": "Sulfato de Protamina."}]', 'D', 'O Sulfato de Protamina se liga à heparina, formando um complexo inativo e neutralizando seu efeito anticoagulante. A Vitamina K é o antídoto para anticoagulantes orais como a Varfarina.', 'Cesgranrio'),
(525, 'Farmacologia', 'Os medicamentos da classe dos Inibidores da Enzima Conversora de Angiotensina (IECA), como Captopril e Enalapril, têm como efeito adverso característico:', '[{"id": "A", "text": "Tosse seca e persistente."}, {"id": "B", "text": "Bradicardia."}, {"id": "C", "text": "Edema de membros inferiores."}, {"id": "D", "text": "Hipocalemia."}]', 'A', 'A tosse seca é um efeito colateral comum e muitas vezes limitante do uso dos IECAs, ocorrendo devido ao acúmulo de bradicinina nos pulmões. É uma das principais causas de troca da medicação por um Bloqueador do Receptor de Angiotensina (BRA).', 'AOCP'),
(526, 'Farmacologia', 'Foi prescrito Penicilina Cristalina 3.000.000 UI. Na unidade, há frascos de 5.000.000 UI. Se você diluir o frasco com 8ml de Água Destilada, qual volume deverá aspirar? (Considere que o pó do frasco de 5M corresponde a 2ml)', '[{"id": "A", "text": "3 ml."}, {"id": "B", "text": "4 ml."}, {"id": "C", "text": "5 ml."}, {"id": "D", "text": "6 ml."}]', 'D', 'Ao diluir com 8ml de AD, o volume final será 8ml (líquido) + 2ml (pó) = 10ml. A concentração será 5.000.000 UI em 10ml. Regra de três: Se 5.000.000 UI --- 10ml, então 3.000.000 UI --- X. X = (3.000.000 * 10) / 5.000.000 = 6 ml.', 'Vunesp'),

-- Imunização
(527, 'Imunização', 'A conservação de vacinas na Rede de Frio exige controle rigoroso de temperatura. Qual a faixa de temperatura ideal para a maioria das vacinas no refrigerador da sala de vacina?', '[{"id": "A", "text": "0°C a +2°C."}, {"id": "B", "text": "+2°C a +8°C."}, {"id": "C", "text": "-15°C a -25°C."}, {"id": "D", "text": "Temperatura ambiente."}]', 'B', 'A temperatura da geladeira da sala de vacinas deve ser mantida rigorosamente entre +2°C e +8°C, sendo o ideal +5°C. Temperaturas negativas (congelamento) inativam a maioria das vacinas.', 'IBFC'),
(528, 'Imunização', 'Quais das seguintes vacinas são contraindicadas para gestantes, por serem de vírus vivo atenuado?', '[{"id": "A", "text": "Hepatite B e dT (Dupla Adulto)."}, {"id": "B", "text": "Tríplice Viral (Sarampo, Caxumba, Rubéola) e Varicela."}, {"id": "C", "text": "dTpa e Influenza."}, {"id": "D", "text": "Raiva e Tétano."}]', 'B', 'Vacinas de vírus vivo atenuado, como a Tríplice Viral (SCR) e a Varicela, são contraindicadas na gestação pelo risco teórico de infecção fetal. Elas devem ser administradas no puerpério, se necessário.', 'FGV'),
(529, 'Imunização', 'Uma criança de 10 meses, sem nenhuma vacina prévia, chega à UBS. Qual o esquema de vacinação inicial recomendado pelo PNI para esta criança?', '[{"id": "A", "text": "Iniciar o calendário como se fosse um recém-nascido."}, {"id": "B", "text": "Aplicar apenas as vacinas recomendadas para a idade de 10 meses."}, {"id": "C", "text": "Aplicar o máximo de vacinas possível para a idade, respeitando os intervalos mínimos."}, {"id": "D", "text": "Aguardar completar 1 ano para iniciar a vacinação."}]', 'C', 'Para crianças com atraso vacinal, o princípio é ''começar de onde parou''. Deve-se aplicar as vacinas correspondentes à idade atual e agendar as doses subsequentes, respeitando os intervalos mínimos entre elas. Não se reinicia o esquema do zero.', 'Cebraspe'),
(530, 'Imunização', 'Um evento adverso pós-vacinação (EAPV) grave, como uma anafilaxia, deve ser notificado em qual sistema de informação?', '[{"id": "A", "text": "SINAN (Sistema de Informação de Agravos de Notificação)."}, {"id": "B", "text": "e-SUS Notifica."}, {"id": "C", "text": "SI-PNI (Sistema de Informação do Programa Nacional de Imunizações)."}, {"id": "D", "text": "SIM (Sistema de Informações sobre Mortalidade)."}]', 'B', 'Desde a pandemia de COVID-19, o sistema e-SUS Notifica foi adaptado e se tornou a plataforma oficial para a notificação de todos os Eventos Adversos Pós-Vacinação (EAPV), não apenas os relacionados à Covid.', 'FCC');