-- Pacote de 20 questões para finalizar o balanceamento de categorias
-- Foco: Saúde da Criança, Saúde da Mulher, Saúde Mental, Administração em Enfermagem, Legislação do SUS

INSERT INTO public.questions (id, category, question, options, "correctAnswer", explanation, banca) VALUES
-- Saúde da Criança
(571, 'Saúde da Criança', 'Qual parâmetro antropométrico é considerado o mais sensível para detectar desnutrição aguda em uma criança?', '[{"id": "A", "text": "Perímetro Cefálico / Idade."}, {"id": "B", "text": "Estatura / Idade."}, {"id": "C", "text": "Peso / Idade."}, {"id": "D", "text": "Peso / Estatura."}]', 'D', 'O índice Peso/Estatura (P/E) reflete a harmonia entre o peso e a altura atuais da criança. Um baixo P/E indica emagrecimento recente ou agudo. O índice Estatura/Idade (E/I) reflete a desnutrição crônica (baixa estatura).', 'FGV'),
(572, 'Saúde da Criança', 'Qual é o marco do desenvolvimento motor esperado para uma criança de 6 a 7 meses de idade?', '[{"id": "A", "text": "Sustentar a cabeça."}, {"id": "B", "text": "Sentar-se sem apoio."}, {"id": "C", "text": "Andar com apoio."}, {"id": "D", "text": "Rolar do decúbito ventral para o dorsal."}]', 'B', 'O marco de sentar-se sem apoio é esperado por volta dos 6 a 7 meses. Sustentar a cabeça ocorre por volta dos 3 meses, e rolar por volta dos 4-5 meses.', 'Cebraspe'),
(573, 'Saúde da Criança', 'Qual dos seguintes sinais é considerado um sinal de gravidade em uma criança com pneumonia, indicando necessidade de referência hospitalar imediata?', '[{"id": "A", "text": "Tosse produtiva."}, {"id": "B", "text": "Febre de 38°C."}, {"id": "C", "text": "Tiragem subcostal."}, {"id": "D", "text": "Coriza."}]', 'C', 'A tiragem subcostal (retração da parte inferior do tórax durante a inspiração) indica esforço respiratório aumentado e é um sinal de gravidade para pneumonia em crianças, segundo as diretrizes da OMS e do Ministério da Saúde.', 'Vunesp'),
(574, 'Saúde da Criança', 'No manejo da diarreia aguda, o Plano C de hidratação do Ministério da Saúde é indicado para qual situação e qual a via de hidratação preconizada?', '[{"id": "A", "text": "Sem desidratação; via oral em casa."}, {"id": "B", "text": "Desidratação leve a moderada; via oral na unidade de saúde."}, {"id": "C", "text": "Desidratação grave; via endovenosa em regime hospitalar."}, {"id": "D", "text": "Qualquer grau de desidratação; via intramuscular."}]', 'C', 'O Plano C é para casos de desidratação grave, com sinais como letargia, olhos fundos, incapacidade de beber líquidos e sinal da prega desaparecendo muito lentamente. A conduta é a hidratação venosa rápida e imediata em ambiente hospitalar.', 'IBFC'),

-- Saúde da Mulher
(575, 'Saúde da Mulher', 'Durante o exame obstétrico, o primeiro tempo das Manobras de Leopold tem como objetivo identificar a:', '[{"id": "A", "text": "Situação fetal (longitudinal, transversa ou oblíqua)."}, {"id": "B", "text": "Posição fetal (dorso à direita ou à esquerda)."}, {"id": "C", "text": "Apresentação fetal (cefálica, pélvica ou córmica)."}, {"id": "D", "text": "Insinuação do feto na pelve materna."}]', 'A', 'O primeiro tempo consiste em delimitar o fundo uterino com ambas as mãos para identificar qual polo fetal (cefálico ou pélvico) o ocupa, determinando assim a situação do feto (sua relação com o eixo longitudinal da mãe).', 'FCC'),
(576, 'Saúde da Mulher', 'Qual é a sequência correta da evolução dos lóquios no puerpério fisiológico?', '[{"id": "A", "text": "Loquia alba -> Loquia serosa -> Loquia rubra."}, {"id": "B", "text": "Loquia serosa -> Loquia rubra -> Loquia alba."}, {"id": "C", "text": "Loquia rubra -> Loquia serosa -> Loquia alba."}, {"id": "D", "text": "Loquia rubra -> Loquia alba -> Loquia serosa."}]', 'C', 'A evolução normal dos lóquios (sangramento pós-parto) é: Loquia rubra (vermelho vivo, até 3-4 dias), Loquia serosa (rosado/acastanhado, até o 10º dia) e Loquia alba (esbranquiçado, após o 10º dia).', 'Cesgranrio'),
(577, 'Saúde da Mulher', 'De acordo com as diretrizes do Ministério da Saúde, qual a faixa etária e a periodicidade recomendada para o rastreamento do câncer de colo de útero com o exame de Papanicolau?', '[{"id": "A", "text": "18 a 59 anos, anualmente."}, {"id": "B", "text": "21 a 65 anos, a cada 3 anos."}, {"id": "C", "text": "25 a 64 anos, sendo os dois primeiros anuais e, se normais, a cada 3 anos."}, {"id": "D", "text": "A partir do início da atividade sexual, anualmente."}]', 'C', 'O rastreamento deve ser feito em mulheres de 25 a 64 anos. A periodicidade é anual nos dois primeiros exames. Se ambos forem negativos, o rastreamento passa a ser a cada 3 anos.', 'AOCP'),
(578, 'Saúde da Mulher', 'Qual o principal mecanismo de ação do Dispositivo Intrauterino (DIU) de Cobre?', '[{"id": "A", "text": "Inibir a ovulação através de hormônios."}, {"id": "B", "text": "Criar uma barreira física que impede a passagem dos espermatozoides."}, {"id": "C", "text": "Liberar íons de cobre que causam uma reação inflamatória no endométrio, tornando-o hostil ao espermatozoide (ação espermicida)."}, {"id": "D", "text": "Espessar o muco cervical, dificultando a subida dos espermatozoides."}]', 'C', 'O DIU de Cobre é um método não hormonal. Sua eficácia se baseia na reação inflamatória asséptica que ele causa no útero, liberando íons de cobre que são tóxicos para os espermatozoides, impedindo a fecundação.', 'IBFC'),

-- Saúde Mental
(579, 'Saúde Mental', 'Na Rede de Atenção Psicossocial (RAPS), qual é a função dos leitos de saúde mental em Hospital Geral?', '[{"id": "A", "text": "Servir como local de internação de longa permanência para casos crônicos."}, {"id": "B", "text": "Atender casos agudos que necessitem de cuidado hospitalar de curta duração, em articulação com o CAPS."}, {"id": "C", "text": "Substituir completamente os hospitais psiquiátricos."}, {"id": "D", "text": "Realizar apenas desintoxicação de álcool e drogas."}]', 'B', 'Os leitos de saúde mental em Hospital Geral são um ponto de atenção da RAPS para o cuidado de pessoas com sofrimento ou transtorno mental e com necessidades de saúde decorrentes do uso de álcool e outras drogas, em situações de crise que necessitem de internação de curta duração.', 'FGV'),
(580, 'Saúde Mental', 'Qual a principal diferença funcional entre um CAPS II e um CAPS III?', '[{"id": "A", "text": "O CAPS II atende crianças e o CAPS III atende adultos."}, {"id": "B", "text": "O CAPS II funciona 8 horas por dia, enquanto o CAPS III funciona 24 horas, incluindo feriados, e possui leitos de acolhimento noturno."}, {"id": "C", "text": "O CAPS II é para cidades pequenas e o CAPS III para metrópoles."}, {"id": "D", "text": "O CAPS II foca em álcool e drogas, e o CAPS III em transtornos mentais gerais."}]', 'B', 'A principal diferença é o funcionamento. O CAPS III é um serviço de funcionamento 24 horas, todos os dias da semana, e dispõe de leitos para acolhimento noturno e observação, sendo estratégico para o cuidado de crises intensas no território.', 'Cebraspe'),
(581, 'Saúde Mental', 'A internação psiquiátrica que ocorre sem o consentimento do paciente, mas a pedido de um familiar ou responsável, é denominada:', '[{"id": "A", "text": "Internação Voluntária."}, {"id": "B", "text": "Internação Involuntária."}, {"id": "C", "text": "Internação Compulsória."}, {"id": "D", "text": "Acolhimento Noturno."}]', 'B', 'A internação involuntária é aquela realizada sem o consentimento do usuário. Ela deve ser solicitada por um terceiro (geralmente familiar) e o Ministério Público deve ser comunicado em até 72 horas.', 'Vunesp'),
(582, 'Saúde Mental', 'Um paciente com esquizofrenia relata ouvir vozes que o comandam. Qual é a conduta de enfermagem mais adequada diante desse relato?', '[{"id": "A", "text": "Confrontar o paciente, dizendo que as vozes não são reais."}, {"id": "B", "text": "Ignorar o relato para não reforçar o sintoma psicótico."}, {"id": "C", "text": "Acolher o relato, validar o sofrimento do paciente e focar na realidade, sem discutir o conteúdo do delírio/alucinação."}, {"id": "D", "text": "Aumentar a dose do antipsicótico por conta própria."}]', 'C', 'A abordagem terapêutica correta é acolher a experiência do paciente (validar que ele está ouvindo algo e que isso o assusta), mas sem validar o conteúdo da alucinação. O foco deve ser em trazer o paciente para a realidade e oferecer suporte, estabelecendo uma relação de confiança.', 'FCC'),

-- Administração em Enfermagem
(583, 'Administração em Enfermagem', 'Em uma situação de emergência, como uma parada cardiorrespiratória, qual estilo de liderança o enfermeiro deve adotar para garantir uma resposta rápida e organizada?', '[{"id": "A", "text": "Liderança Democrática."}, {"id": "B", "text": "Liderança Liberal (Laissez-faire)."}, {"id": "C", "text": "Liderança Autocrática."}, {"id": "D", "text": "Liderança Situacional."}]', 'C', 'A liderança autocrática, onde o líder centraliza as decisões e dá ordens diretas, é a mais eficaz em situações de emergência que exigem ações rápidas e coordenadas, como uma PCR. Nos outros momentos, outros estilos podem ser mais adequados.', 'IBFC'),
(584, 'Administração em Enfermagem', 'A Teoria das Relações Humanas, iniciada com os estudos de Elton Mayo, trouxe uma nova perspectiva para a administração, valorizando:', '[{"id": "A", "text": "A eficiência máxima da tarefa e a padronização dos movimentos."}, {"id": "B", "text": "A estrutura organizacional formal e a hierarquia rígida."}, {"id": "C", "text": "Os aspectos psicológicos, a integração social e a importância dos grupos informais."}, {"id": "D", "text": "A burocracia e a impessoalidade nas relações de trabalho."}]', 'C', 'A Teoria das Relações Humanas surgiu como uma oposição à abordagem mecanicista da Teoria Clássica, destacando que a produtividade está mais ligada a fatores sociais e psicológicos (motivação, satisfação, reconhecimento) do que a fatores físicos.', 'Cesgranrio'),
(585, 'Administração em Enfermagem', 'Em auditoria de contas hospitalares, o não pagamento de um item ou procedimento por não conformidade com as normas ou com o contrato é denominado:', '[{"id": "A", "text": "Glosa."}, {"id": "B", "text": "Fatura."}, {"id": "C", "text": "Recurso."}, {"id": "D", "text": "Parecer."}]', 'A', 'Glosa é o termo técnico utilizado em auditoria para o cancelamento total ou parcial do pagamento de despesas apresentadas pelo prestador de serviço, devido a irregularidades ou não conformidades.', 'AOCP'),
(586, 'Administração em Enfermagem', 'Qual a principal diferença conceitual entre Educação Permanente em Saúde e Educação Continuada?', '[{"id": "A", "text": "Educação Continuada é mais longa que a Permanente."}, {"id": "B", "text": "Educação Permanente parte da problematização do processo de trabalho, enquanto a Continuada foca na atualização técnica pontual."}, {"id": "C", "text": "Apenas a Educação Permanente oferece certificado."}, {"id": "D", "text": "Educação Continuada é para enfermeiros e a Permanente para técnicos."}]', 'B', 'A Educação Continuada são atividades pontuais de atualização (cursos, palestras). A Educação Permanente é um processo contínuo que ocorre no cotidiano do trabalho, partindo dos problemas enfrentados pela equipe para transformar a prática.', 'IBFC'),

-- Legislação do SUS
(587, 'Legislação do SUS', 'As Comissões Intergestores Bipartite (CIB) e Tripartite (CIT) são instâncias do SUS com a principal função de:', '[{"id": "A", "text": "Fiscalizar a aplicação dos recursos financeiros pelos municípios."}, {"id": "B", "text": "Julgar processos éticos de profissionais de saúde."}, {"id": "C", "text": "Servir como foro de negociação e pactuação entre os gestores das três esferas de governo."}, {"id": "D", "text": "Definir o calendário nacional de vacinação."}]', 'C', 'As Comissões Intergestores (CIB no âmbito estadual, CIT no âmbito nacional) são espaços fundamentais para a negociação e o acordo entre os gestores (secretários de saúde) sobre os aspectos operacionais e financeiros da gestão compartilhada do SUS.', 'FGV'),
(588, 'Legislação do SUS', 'De acordo com o Decreto 7.508/2011, o que é o Mapa da Saúde?', '[{"id": "A", "text": "O organograma da Secretaria de Saúde."}, {"id": "B", "text": "A descrição geográfica da distribuição de recursos humanos e de ações e serviços de saúde ofertados."}, {"id": "C", "text": "O plano de carreira dos profissionais do SUS."}, {"id": "D", "text": "A lista de doenças de notificação compulsória."}]', 'B', 'O Mapa da Saúde é uma ferramenta de planejamento que descreve a capacidade instalada (leitos, equipamentos, profissionais) e os serviços disponíveis em uma determinada região, orientando a identificação de vazios assistenciais e a alocação de recursos.', 'Cebraspe'),
(589, 'Legislação do SUS', 'A Lei 8.142/90 estabelece a composição paritária para os Conselhos de Saúde. Isso significa que a representação dos usuários deve ser de:', '[{"id": "A", "text": "25% do total de vagas."}, {"id": "B", "text": "50% do total de vagas."}, {"id": "C", "text": "75% do total de vagas."}, {"id": "D", "text": "Proporcional ao número de habitantes."}]', 'B', 'A paridade nos Conselhos e Conferências de Saúde significa que 50% das vagas são destinadas aos representantes dos usuários. Os outros 50% são divididos entre trabalhadores da saúde (25%) e gestores/prestadores de serviço (25%).', 'Vunesp'),
(590, 'Legislação do SUS', 'Segundo a Política Nacional de Atenção Básica (PNAB), qual é a composição mínima de uma Equipe de Saúde da Família (eSF)?', '[{"id": "A", "text": "Médico, Enfermeiro e Agente Comunitário de Saúde (ACS)."}, {"id": "B", "text": "Médico, Enfermeiro, Técnico de Enfermagem e Dentista."}, {"id": "C", "text": "Médico, Enfermeiro, Técnico ou Auxiliar de Enfermagem e Agente Comunitário de Saúde (ACS)."}, {"id": "D", "text": "Enfermeiro, Técnico de Enfermagem, ACS e Fisioterapeuta."}]', 'C', 'A composição mínima obrigatória da eSF é: Médico (preferencialmente especialista em Saúde da Família), Enfermeiro (preferencialmente especialista), Técnico ou Auxiliar de Enfermagem e Agentes Comunitários de Saúde. Profissionais de saúde bucal podem ser adicionados.', 'FCC');